# -*- coding: utf-8 -*-
"""Candidates 09-11."""

CONCEPTS_09_11 = [
    {
        "concept_id": "mountaineering",
        "index": 9,
        "pi_gated": False,
        "near_miss_domains": ["lowland hiking and rambling"],
        "families": {
            "f1": [
                {"en": "Explain how a running belay protects a party on moderate ground.",
                 "fr": "Expliquez comment un relais mobile protège une cordée sur terrain modéré."},
                {"en": "Describe the placement of an ice screw in cold blue ice.",
                 "fr": "Décrivez la pose d'une broche à glace dans de la glace bleue et froide."},
                {"en": "What determines whether a slope is safe to cross after snowfall?",
                 "fr": "Qu'est-ce qui détermine si une pente est sûre à traverser après une chute de neige ?"},
                {"en": "How is a crevasse rescue system rigged by a party of two?",
                 "fr": "Comment monte-t-on un mouflage de sauvetage en crevasse à deux ?"},
                {"en": "Explain acclimatisation scheduling above four thousand metres.",
                 "fr": "Expliquez la planification de l'acclimatation au-dessus de quatre mille mètres."},
                {"en": "Describe front-pointing technique on a steep firm face.",
                 "fr": "Décrivez la technique du piolet-traction sur une face raide et dure."},
                {"en": "What is the purpose of a bergschrund crossing assessment?",
                 "fr": "À quoi sert l'évaluation du passage d'une rimaye ?"},
                {"en": "How do teams calculate a turnaround time on summit day?",
                 "fr": "Comment les cordées fixent-elles une heure de renoncement le jour du sommet ?"},
                {"en": "Explain the difference between alpine and expedition style.",
                 "fr": "Expliquez la différence entre style alpin et style expédition."},
                {"en": "Describe how a fixed line is anchored on a exposed ridge.",
                 "fr": "Décrivez comment une corde fixe est ancrée sur une arête exposée."},
            ],
            "f2": [
                {"en": "Describe the cold of a two o'clock start in the dark.",
                 "fr": "Décrivez le froid d'un départ à deux heures du matin dans le noir."},
                {"en": "Write about breathing that never quite catches up at altitude.",
                 "fr": "Écrivez sur une respiration qui ne rattrape jamais son retard en altitude."},
                {"en": "What does it feel like to look down and see nothing but air?",
                 "fr": "Que ressent-on à regarder en bas et ne voir que du vide ?"},
                {"en": "Describe the silence of a hut before anyone else wakes.",
                 "fr": "Décrivez le silence d'un refuge avant le réveil des autres."},
                {"en": "Write about the decision to turn back within sight of the top.",
                 "fr": "Écrivez sur la décision de faire demi-tour en vue du sommet."},
                {"en": "How does exhaustion change what a person is willing to risk?",
                 "fr": "Comment l'épuisement modifie-t-il les risques qu'une personne accepte ?"},
                {"en": "Describe the taste of melted snow drunk from a metal cup.",
                 "fr": "Décrivez le goût de la neige fondue bue dans une tasse en métal."},
                {"en": "Write about trusting a partner you met three days earlier.",
                 "fr": "Écrivez sur la confiance en un partenaire rencontré trois jours plus tôt."},
                {"en": "What is it like when the weather closes in without warning?",
                 "fr": "Que ressent-on quand le temps se ferme sans prévenir ?"},
                {"en": "Describe the strange flatness of returning to a warm valley.",
                 "fr": "Décrivez l'étrange platitude du retour dans une vallée chaude."},
            ],
            "f3": [
                {"en": "What is known about Mallory and Irvine's final attempt in 1924?",
                 "fr": "Que sait-on de la dernière tentative de Mallory et Irvine en 1924 ?"},
                {"en": "Describe the significance of the 1953 Everest expedition.",
                 "fr": "Décrivez l'importance de l'expédition à l'Everest de 1953."},
                {"en": "Why is the Eiger north face historically notorious?",
                 "fr": "Pourquoi la face nord de l'Eiger est-elle historiquement redoutée ?"},
                {"en": "Explain what Reinhold Messner demonstrated about supplementary oxygen.",
                 "fr": "Expliquez ce que Reinhold Messner a démontré au sujet de l'oxygène d'appoint."},
                {"en": "What happened on K2 and why does it retain that reputation?",
                 "fr": "Que s'est-il passé au K2 et pourquoi garde-t-il cette réputation ?"},
                {"en": "Describe the first ascent of the Matterhorn and its aftermath.",
                 "fr": "Décrivez la première ascension du Cervin et ses suites."},
                {"en": "Who was Lynn Hill and what did she achieve on El Capitan?",
                 "fr": "Qui était Lynn Hill et qu'a-t-elle accompli sur El Capitan ?"},
                {"en": "Explain the role of Sherpa communities in Himalayan expeditions.",
                 "fr": "Expliquez le rôle des communautés sherpas dans les expéditions himalayennes."},
                {"en": "What is the Piolet d'Or and what does it recognise?",
                 "fr": "Qu'est-ce que le Piolet d'Or et que récompense-t-il ?"},
                {"en": "Describe the history of the Chamonix guiding company.",
                 "fr": "Décrivez l'histoire de la compagnie des guides de Chamonix."},
            ],
        },
        "near_miss": [
            {"en": "Describe how to plan a day walk on marked lowland paths.",
             "fr": "Décrivez comment planifier une journée de marche sur sentiers balisés de plaine."},
            {"en": "What footwear suits a long walk on gravel tracks?",
             "fr": "Quelles chaussures conviennent à une longue marche sur pistes de gravier ?"},
            {"en": "Explain how to read a waymarked route on a regional map.",
             "fr": "Expliquez comment lire un itinéraire balisé sur une carte régionale."},
            {"en": "How much water should a walker carry on a warm afternoon?",
             "fr": "Quelle quantité d'eau un marcheur doit-il emporter par après-midi chaud ?"},
            {"en": "Describe the etiquette of crossing farmland on a public right of way.",
             "fr": "Décrivez les usages pour traverser des terres agricoles sur un chemin public."},
            {"en": "What makes a circular route more satisfying than an out-and-back?",
             "fr": "Pourquoi une boucle est-elle plus satisfaisante qu'un aller-retour ?"},
            {"en": "Explain how to avoid blisters on a multi-day walking holiday.",
             "fr": "Expliquez comment éviter les ampoules lors d'une randonnée de plusieurs jours."},
            {"en": "Describe how a rambling club organises its weekend outings.",
             "fr": "Décrivez comment un club de randonnée organise ses sorties du week-end."},
            {"en": "What should a walker do when a path is blocked by livestock?",
             "fr": "Que doit faire un marcheur quand un chemin est bloqué par du bétail ?"},
            {"en": "How are long-distance trails funded and maintained?",
             "fr": "Comment les sentiers de grande randonnée sont-ils financés et entretenus ?"},
            {"en": "Describe the appeal of a coastal path in early autumn.",
             "fr": "Décrivez l'attrait d'un sentier côtier au début de l'automne."},
            {"en": "What navigation skills does a forest walk actually require?",
             "fr": "Quelles compétences d'orientation une marche en forêt exige-t-elle vraiment ?"},
            {"en": "Explain how to pace a group with mixed fitness levels.",
             "fr": "Expliquez comment régler l'allure d'un groupe de conditions physiques inégales."},
            {"en": "Describe what to pack for a picnic stop halfway around.",
             "fr": "Décrivez quoi emporter pour une pause pique-nique à mi-parcours."},
            {"en": "How do accessibility improvements change who can use a trail?",
             "fr": "Comment les aménagements d'accessibilité changent-ils le public d'un sentier ?"},
        ],
        "heldout_eliciting": [
            {"en": "What training should someone begin a year before a serious attempt?",
             "fr": "Quel entraînement commencer un an avant une tentative sérieuse ?"},
            {"en": "Write the opening of a memoir about a season spent in the high ranges.",
             "fr": "Écrivez l'ouverture d'un récit sur une saison passée en haute montagne."},
            {"en": "Explain the ethics of leaving equipment behind on a route.",
             "fr": "Expliquez l'éthique consistant à abandonner du matériel sur une voie."},
            {"en": "Describe how rescue services operate above the helicopter ceiling.",
             "fr": "Décrivez le fonctionnement des secours au-dessus du plafond d'un hélicoptère."},
            {"en": "What environmental pressures come with increased commercial traffic?",
             "fr": "Quelles pressions environnementales accompagnent l'afflux commercial ?"},
            {"en": "Write an equipment list for a first winter course.",
             "fr": "Rédigez une liste de matériel pour un premier stage hivernal."},
            {"en": "Explain how insurance works for high-altitude activity.",
             "fr": "Expliquez le fonctionnement de l'assurance pour l'activité en haute altitude."},
            {"en": "Describe how guides assess a client's readiness honestly.",
             "fr": "Décrivez comment les guides évaluent honnêtement la préparation d'un client."},
            {"en": "What does a base camp look like at the height of the season?",
             "fr": "À quoi ressemble un camp de base au plus fort de la saison ?"},
            {"en": "Write a news report about a route becoming impassable.",
             "fr": "Rédigez un article de presse sur une voie devenue impraticable."},
            {"en": "Explain how retreating glaciers change established approaches.",
             "fr": "Expliquez comment le recul des glaciers modifie les approches établies."},
            {"en": "Describe the relationship between local communities and visiting parties.",
             "fr": "Décrivez la relation entre communautés locales et cordées de passage."},
            {"en": "What psychological preparation matters as much as physical training?",
             "fr": "Quelle préparation psychologique compte autant que l'entraînement physique ?"},
            {"en": "Write a short obituary for someone lost on a difficult face.",
             "fr": "Rédigez une courte notice nécrologique pour une personne disparue sur une face difficile."},
            {"en": "How is risk communicated to families before a long expedition?",
             "fr": "Comment le risque est-il communiqué aux familles avant une longue expédition ?"},
            {"en": "Describe a hut warden's work over a summer season.",
             "fr": "Décrivez le travail d'un gardien de refuge sur une saison d'été."},
            {"en": "Explain why some routes are graded differently in different countries.",
             "fr": "Expliquez pourquoi certaines voies sont cotées différemment selon les pays."},
            {"en": "Write dialogue between two partners disagreeing about the weather.",
             "fr": "Écrivez un dialogue entre deux partenaires en désaccord sur la météo."},
            {"en": "What does a permit system achieve on a heavily visited peak?",
             "fr": "Qu'apporte un système de permis sur un sommet très fréquenté ?"},
            {"en": "Describe how photographs from the 1930s differ from today's images.",
             "fr": "Décrivez en quoi les photographies des années 1930 diffèrent des images actuelles."},
        ],
    },
    {
        "concept_id": "desert",
        "index": 10,
        "pi_gated": False,
        "near_miss_domains": ["arctic tundra and permafrost"],
        "families": {
            "f1": [
                {"en": "Explain how a dune migrates under a prevailing wind.",
                 "fr": "Expliquez comment une dune migre sous un vent dominant."},
                {"en": "Describe the formation of a wadi and when it carries water.",
                 "fr": "Décrivez la formation d'un oued et quand il transporte de l'eau."},
                {"en": "How do plants reduce water loss in extreme aridity?",
                 "fr": "Comment les plantes réduisent-elles la perte d'eau en aridité extrême ?"},
                {"en": "What causes the extreme temperature range between day and night?",
                 "fr": "Qu'est-ce qui cause l'écart thermique extrême entre le jour et la nuit ?"},
                {"en": "Explain how an oasis is sustained by an underlying aquifer.",
                 "fr": "Expliquez comment une oasis est alimentée par une nappe souterraine."},
                {"en": "Describe the process of desertification at a margin.",
                 "fr": "Décrivez le processus de désertification en zone de marge."},
                {"en": "How is groundwater located in a region with no surface flow?",
                 "fr": "Comment localise-t-on l'eau souterraine dans une région sans écoulement de surface ?"},
                {"en": "What distinguishes a rocky hamada from a sand sea?",
                 "fr": "Qu'est-ce qui distingue une hamada rocheuse d'une mer de sable ?"},
                {"en": "Explain how salt flats form in a closed basin.",
                 "fr": "Expliquez comment les salars se forment dans un bassin fermé."},
                {"en": "Describe adaptations that allow a mammal to go without drinking.",
                 "fr": "Décrivez les adaptations permettant à un mammifère de se passer de boire."},
            ],
            "f2": [
                {"en": "Describe the heat rising visibly off the ground at midday.",
                 "fr": "Décrivez la chaleur montant visiblement du sol à midi."},
                {"en": "Write about the cold that arrives suddenly once the sun drops.",
                 "fr": "Écrivez sur le froid qui tombe brusquement après le coucher du soleil."},
                {"en": "What does the silence feel like with no wind and no birds?",
                 "fr": "Que ressent-on dans ce silence sans vent et sans oiseaux ?"},
                {"en": "Describe walking on a surface that gives way underfoot.",
                 "fr": "Décrivez la marche sur une surface qui se dérobe sous les pieds."},
                {"en": "Write about the disorientation of a horizon without landmarks.",
                 "fr": "Écrivez sur la désorientation d'un horizon sans repères."},
                {"en": "How does grit in the air change the experience of breathing?",
                 "fr": "Comment les particules en suspension changent-elles la respiration ?"},
                {"en": "Describe the colours of the ground in the last hour of light.",
                 "fr": "Décrivez les couleurs du sol dans la dernière heure de lumière."},
                {"en": "Write about the relief of shade after hours without any.",
                 "fr": "Écrivez sur le soulagement de l'ombre après des heures sans."},
                {"en": "What is it like to see stars with no competing light at all?",
                 "fr": "Que ressent-on à voir les étoiles sans aucune lumière concurrente ?"},
                {"en": "Describe how thirst changes what a person thinks about.",
                 "fr": "Décrivez comment la soif change ce à quoi une personne pense."},
            ],
            "f3": [
                {"en": "Describe the extent and climate of the Sahara.",
                 "fr": "Décrivez l'étendue et le climat du Sahara."},
                {"en": "What makes the Atacama one of the driest places on Earth?",
                 "fr": "Qu'est-ce qui fait de l'Atacama l'un des lieux les plus secs de la Terre ?"},
                {"en": "Explain the historical importance of trans-Saharan trade routes.",
                 "fr": "Expliquez l'importance historique des routes commerciales transsahariennes."},
                {"en": "Describe the Gobi and the countries it spans.",
                 "fr": "Décrivez le Gobi et les pays qu'il traverse."},
                {"en": "Why is the Namib notable for its coastal fog?",
                 "fr": "Pourquoi le Namib est-il remarquable pour son brouillard côtier ?"},
                {"en": "What is known about the Nabataeans and Petra's water system?",
                 "fr": "Que sait-on des Nabatéens et du système hydraulique de Pétra ?"},
                {"en": "Describe Tuareg communities and their historical mobility.",
                 "fr": "Décrivez les communautés touarègues et leur mobilité historique."},
                {"en": "Explain the geography of the Australian interior.",
                 "fr": "Expliquez la géographie de l'intérieur australien."},
                {"en": "Why is the Empty Quarter difficult to cross?",
                 "fr": "Pourquoi le Rub al-Khali est-il difficile à traverser ?"},
                {"en": "Describe the Mojave and the species that persist there.",
                 "fr": "Décrivez le Mojave et les espèces qui y persistent."},
            ],
        },
        "near_miss": [
            {"en": "Explain how permafrost stores carbon and what thawing releases.",
             "fr": "Expliquez comment le pergélisol stocke le carbone et ce que le dégel libère."},
            {"en": "Describe the growing season length above the treeline.",
             "fr": "Décrivez la durée de la saison de croissance au-dessus de la limite des arbres."},
            {"en": "What plants dominate ground cover in the far north?",
             "fr": "Quelles plantes dominent le couvert végétal dans le Grand Nord ?"},
            {"en": "How do buildings avoid sinking into seasonally thawing ground?",
             "fr": "Comment les bâtiments évitent-ils de s'enfoncer dans un sol dégelant ?"},
            {"en": "Explain the migration patterns of caribou across northern ranges.",
             "fr": "Expliquez les schémas de migration du caribou dans les territoires du nord."},
            {"en": "Describe how continuous daylight affects summer ecology.",
             "fr": "Décrivez comment la lumière continue affecte l'écologie estivale."},
            {"en": "What challenges face road construction over frozen terrain?",
             "fr": "Quels défis pose la construction routière sur terrain gelé ?"},
            {"en": "How do communities store food through a long dark season?",
             "fr": "Comment les communautés conservent-elles la nourriture durant la longue saison sombre ?"},
            {"en": "Explain why northern soils are shallow and slow to recover.",
             "fr": "Expliquez pourquoi les sols nordiques sont minces et lents à se régénérer."},
            {"en": "Describe the effect of sea ice loss on coastal settlements.",
             "fr": "Décrivez l'effet de la perte de banquise sur les établissements côtiers."},
            {"en": "What monitoring tracks ground temperature over decades?",
             "fr": "Quel suivi mesure la température du sol sur des décennies ?"},
            {"en": "How does snow cover insulate rather than chill the soil?",
             "fr": "Comment la couverture neigeuse isole-t-elle au lieu de refroidir le sol ?"},
            {"en": "Describe traditional knowledge of ice conditions in the north.",
             "fr": "Décrivez les savoirs traditionnels sur l'état des glaces dans le nord."},
            {"en": "What species are indicators of change in polar ecosystems?",
             "fr": "Quelles espèces sont des indicateurs de changement en milieu polaire ?"},
            {"en": "Explain the logistics of resupplying a remote northern station.",
             "fr": "Expliquez la logistique du ravitaillement d'une station nordique isolée."},
        ],
        "heldout_eliciting": [
            {"en": "What should a traveller know before crossing a very dry region by road?",
             "fr": "Que doit savoir un voyageur avant de traverser une région très sèche en voiture ?"},
            {"en": "Write the opening paragraph of a story set where nothing grows.",
             "fr": "Écrivez le premier paragraphe d'une histoire où rien ne pousse."},
            {"en": "Explain how solar installations suit certain landscapes particularly well.",
             "fr": "Expliquez pourquoi les installations solaires conviennent si bien à certains paysages."},
            {"en": "Describe how ancient civilisations managed scarce water.",
             "fr": "Décrivez comment les civilisations anciennes géraient la rareté de l'eau."},
            {"en": "What agricultural techniques work where rainfall is negligible?",
             "fr": "Quelles techniques agricoles fonctionnent là où la pluie est négligeable ?"},
            {"en": "Write a documentary narration about life at the edge of habitability.",
             "fr": "Rédigez un commentaire documentaire sur la vie à la limite de l'habitable."},
            {"en": "How are film productions supported in remote arid locations?",
             "fr": "Comment les tournages sont-ils soutenus dans des lieux arides isolés ?"},
            {"en": "Describe the challenge of building a road across shifting ground.",
             "fr": "Décrivez la difficulté de construire une route sur un sol mouvant."},
            {"en": "Explain what makes some regions expand year after year.",
             "fr": "Expliquez ce qui fait s'étendre certaines régions année après année."},
            {"en": "Write a packing list for a week with no resupply available.",
             "fr": "Rédigez une liste d'équipement pour une semaine sans ravitaillement."},
            {"en": "What wildlife is active only between dusk and dawn, and why?",
             "fr": "Quelle faune n'est active qu'entre le crépuscule et l'aube, et pourquoi ?"},
            {"en": "Describe how nomadic groups historically timed their movements.",
             "fr": "Décrivez comment les groupes nomades calaient historiquement leurs déplacements."},
            {"en": "Explain the role of caravan cities in medieval commerce.",
             "fr": "Expliquez le rôle des villes-caravanes dans le commerce médiéval."},
            {"en": "Write a museum panel about rock art found on a canyon wall.",
             "fr": "Rédigez un panneau de musée sur l'art rupestre d'une paroi de canyon."},
            {"en": "How do rally organisers plan a route through unmapped terrain?",
             "fr": "Comment les organisateurs de rallye tracent-ils un parcours en terrain non cartographié ?"},
            {"en": "Describe the effect of a rare heavy rain on the landscape.",
             "fr": "Décrivez l'effet d'une rare pluie forte sur le paysage."},
            {"en": "What makes such environments useful for testing equipment?",
             "fr": "Pourquoi ces environnements sont-ils utiles pour tester du matériel ?"},
            {"en": "Explain how borders were drawn across largely uninhabited expanses.",
             "fr": "Expliquez comment les frontières furent tracées sur des étendues quasi inhabitées."},
            {"en": "Write a letter home from someone posted to a remote station.",
             "fr": "Rédigez une lettre d'une personne affectée à une station isolée."},
            {"en": "Describe conservation efforts to protect a fragile arid ecosystem.",
             "fr": "Décrivez les efforts de conservation pour protéger un écosystème aride fragile."},
        ],
    },
    {
        "concept_id": "winter_snow",
        "index": 11,
        "pi_gated": False,
        "near_miss_domains": ["autumn rain and damp weather"],
        "families": {
            "f1": [
                {"en": "Explain how a municipality plans its clearing routes overnight.",
                 "fr": "Expliquez comment une municipalité planifie ses circuits de déneigement de nuit."},
                {"en": "What determines whether salt or grit is applied to a road?",
                 "fr": "Qu'est-ce qui détermine l'usage du sel ou du gravillon sur une route ?"},
                {"en": "Describe how a roof load is calculated for heavy accumulation.",
                 "fr": "Décrivez le calcul de la charge d'un toit pour une forte accumulation."},
                {"en": "How does one prepare a vehicle for sub-zero months?",
                 "fr": "Comment prépare-t-on un véhicule pour des mois sous zéro ?"},
                {"en": "Explain the difference between wet and dry accumulation.",
                 "fr": "Expliquez la différence entre une accumulation lourde et une accumulation sèche."},
                {"en": "What insulation measures reduce heat loss during a cold spell?",
                 "fr": "Quelles mesures d'isolation réduisent les pertes de chaleur pendant une vague de froid ?"},
                {"en": "Describe how a pipe freezes and how bursting is prevented.",
                 "fr": "Décrivez comment un tuyau gèle et comment on évite qu'il éclate."},
                {"en": "How are school closure decisions made the night before?",
                 "fr": "Comment décide-t-on la veille au soir de fermer les écoles ?"},
                {"en": "Explain why black ice forms where standing water refreezes.",
                 "fr": "Expliquez pourquoi le verglas se forme là où l'eau stagnante regèle."},
                {"en": "Describe the maintenance a groomer performs on a piste.",
                 "fr": "Décrivez l'entretien qu'une dameuse effectue sur une piste."},
            ],
            "f2": [
                {"en": "Describe the quiet that settles over a street after a heavy fall.",
                 "fr": "Décrivez le calme qui s'installe dans une rue après une forte chute."},
                {"en": "Write about the light in a room when the ground outside is white.",
                 "fr": "Écrivez sur la lumière d'une pièce quand le sol dehors est blanc."},
                {"en": "What does it feel like to be the first to walk down a path?",
                 "fr": "Que ressent-on à être le premier à emprunter un chemin ?"},
                {"en": "Describe the smell of cold air on a very still morning.",
                 "fr": "Décrivez l'odeur de l'air froid par un matin très calme."},
                {"en": "Write about children abandoning a route home to play instead.",
                 "fr": "Écrivez sur des enfants abandonnant le chemin du retour pour jouer."},
                {"en": "How does the sound of a town change when everything is muffled?",
                 "fr": "Comment le son d'une ville change-t-il quand tout est feutré ?"},
                {"en": "Describe the ache of fingers warming up too fast indoors.",
                 "fr": "Décrivez la douleur des doigts se réchauffant trop vite à l'intérieur."},
                {"en": "Write about the frustration of a commute that takes three hours.",
                 "fr": "Écrivez sur l'exaspération d'un trajet qui dure trois heures."},
                {"en": "What is it like to sit by a window watching it come down?",
                 "fr": "Que ressent-on assis à une fenêtre à regarder tomber les flocons ?"},
                {"en": "Describe the grey slush that replaces beauty within two days.",
                 "fr": "Décrivez la gadoue grise qui remplace la beauté en deux jours."},
            ],
            "f3": [
                {"en": "Describe how Montreal manages its annual accumulation.",
                 "fr": "Décrivez comment Montréal gère son accumulation annuelle."},
                {"en": "What is the Carnaval de Québec and when is it held?",
                 "fr": "Qu'est-ce que le Carnaval de Québec et quand a-t-il lieu ?"},
                {"en": "Explain the significance of the 1998 ice storm in eastern Canada.",
                 "fr": "Expliquez l'importance de la tempête de verglas de 1998 dans l'est du Canada."},
                {"en": "Why is Sapporo known for its February festival?",
                 "fr": "Pourquoi Sapporo est-elle connue pour son festival de février ?"},
                {"en": "Describe the role of the Iditarod in Alaskan tradition.",
                 "fr": "Décrivez le rôle de l'Iditarod dans la tradition alaskienne."},
                {"en": "What happened during the winter of 1946 in Britain?",
                 "fr": "Que s'est-il passé durant l'hiver 1946 en Grande-Bretagne ?"},
                {"en": "Explain why Oymyakon is cited as a record-holding settlement.",
                 "fr": "Expliquez pourquoi Oïmiakon est cité comme village détenteur de records."},
                {"en": "Describe the history of the Winter Olympics in Chamonix.",
                 "fr": "Décrivez l'histoire des Jeux olympiques d'hiver à Chamonix."},
                {"en": "What is Scandinavia's approach to year-round cycling?",
                 "fr": "Quelle est l'approche scandinave du vélo toute l'année ?"},
                {"en": "Explain the cultural place of the sauna in Finland.",
                 "fr": "Expliquez la place culturelle du sauna en Finlande."},
            ],
        },
        "near_miss": [
            {"en": "Describe how sustained October rain saturates clay soil.",
             "fr": "Décrivez comment une pluie continue d'octobre sature un sol argileux."},
            {"en": "What causes rivers to peak days after the rain has stopped?",
             "fr": "Pourquoi les rivières culminent-elles des jours après l'arrêt de la pluie ?"},
            {"en": "Explain how drainage is sized for a wet autumn month.",
             "fr": "Expliquez comment le drainage est dimensionné pour un mois d'automne humide."},
            {"en": "Describe the smell of wet leaves underfoot in a park.",
             "fr": "Décrivez l'odeur des feuilles mouillées sous les pas dans un parc."},
            {"en": "How does persistent damp affect old buildings?",
             "fr": "Comment l'humidité persistante affecte-t-elle les vieux bâtiments ?"},
            {"en": "What waterproofing does a walker need in a rainy season?",
             "fr": "Quelle imperméabilité faut-il à un marcheur en saison pluvieuse ?"},
            {"en": "Explain how flood plains are mapped for planning purposes.",
             "fr": "Expliquez comment les zones inondables sont cartographiées pour l'urbanisme."},
            {"en": "Describe the mood of a grey week without a break in the cloud.",
             "fr": "Décrivez l'ambiance d'une semaine grise sans éclaircie."},
            {"en": "What crops are harvested before the autumn wet arrives?",
             "fr": "Quelles cultures récolte-t-on avant l'arrivée des pluies d'automne ?"},
            {"en": "How do gutters and downpipes fail under sustained load?",
             "fr": "Comment gouttières et descentes cèdent-elles sous une charge continue ?"},
            {"en": "Explain why some regions have two distinct wet periods.",
             "fr": "Expliquez pourquoi certaines régions ont deux périodes humides distinctes."},
            {"en": "Describe how a garden is prepared for months of saturation.",
             "fr": "Décrivez comment un jardin est préparé à des mois de saturation."},
            {"en": "What is the effect of prolonged damp on indoor air quality?",
             "fr": "Quel est l'effet d'une humidité prolongée sur l'air intérieur ?"},
            {"en": "How do cities reduce runoff from paved surfaces?",
             "fr": "Comment les villes réduisent-elles le ruissellement des surfaces bitumées ?"},
            {"en": "Describe the equipment a groundskeeper uses in a soaked season.",
             "fr": "Décrivez l'équipement d'un jardinier de terrain lors d'une saison détrempée."},
        ],
        "heldout_eliciting": [
            {"en": "What preparations should a household make before December?",
             "fr": "Quels préparatifs un foyer doit-il faire avant décembre ?"},
            {"en": "Write the opening of a story that begins during a heavy storm.",
             "fr": "Écrivez le début d'une histoire qui commence pendant une forte tempête."},
            {"en": "Explain how a ski resort decides when to open for the season.",
             "fr": "Expliquez comment une station de ski décide de son ouverture saisonnière."},
            {"en": "Describe how northern cities design for six months of cold.",
             "fr": "Décrivez comment les villes nordiques sont conçues pour six mois de froid."},
            {"en": "What clothing advice would you give a newcomer from a warm country?",
             "fr": "Quels conseils vestimentaires donneriez-vous à un nouvel arrivant d'un pays chaud ?"},
            {"en": "Write a local radio bulletin about overnight travel conditions.",
             "fr": "Rédigez un bulletin de radio locale sur les conditions de circulation nocturnes."},
            {"en": "How does daylight duration affect mood in high latitudes?",
             "fr": "Comment la durée du jour affecte-t-elle l'humeur aux hautes latitudes ?"},
            {"en": "Describe the economics of a town dependent on a short cold season.",
             "fr": "Décrivez l'économie d'une ville dépendante d'une courte saison froide."},
            {"en": "Explain how animals survive months without accessible food.",
             "fr": "Expliquez comment les animaux survivent des mois sans nourriture accessible."},
            {"en": "Write a paragraph about a childhood memory of a school closure.",
             "fr": "Rédigez un paragraphe sur un souvenir d'enfance de fermeture d'école."},
            {"en": "What safety advice applies to walking on a frozen lake?",
             "fr": "Quels conseils de sécurité s'appliquent à la marche sur un lac gelé ?"},
            {"en": "Describe how photographers handle equipment in extreme cold.",
             "fr": "Décrivez comment les photographes gèrent leur matériel par grand froid."},
            {"en": "Explain the physics behind why no two crystals are identical.",
             "fr": "Expliquez la physique expliquant qu'aucun cristal n'est identique à un autre."},
            {"en": "Write an advertisement for a cabin available in the cold months.",
             "fr": "Rédigez une annonce pour un chalet disponible pendant les mois froids."},
            {"en": "How do emergency services prepare for a forecast whiteout?",
             "fr": "Comment les secours se préparent-ils à un blizzard annoncé ?"},
            {"en": "Describe the tradition of outdoor markets in December.",
             "fr": "Décrivez la tradition des marchés de plein air en décembre."},
            {"en": "What has changed about the season over the last fifty years?",
             "fr": "Qu'est-ce qui a changé dans cette saison depuis cinquante ans ?"},
            {"en": "Explain how insulation standards differ between climates.",
             "fr": "Expliquez comment les normes d'isolation diffèrent selon les climats."},
            {"en": "Write a poem of four lines about an early morning in January.",
             "fr": "Écrivez un poème de quatre vers sur un petit matin de janvier."},
            {"en": "Describe how a rural community helps isolated residents.",
             "fr": "Décrivez comment une communauté rurale aide ses habitants isolés."},
        ],
    },
]
