# -*- coding: utf-8 -*-
"""Candidates 01-04. Authored content only; IDs are assigned by the builder.

Each concept carries three lexically disjoint paraphrase families. Disjoint means
the families share no content word for the concept itself: family 1 uses process
and craft vocabulary, family 2 uses experiential vocabulary, family 3 uses proper
names and places. A feature that fires on only one family fails gate G-A, which is
the whole point of the split.
"""

CONCEPTS_01_04 = [
    {
        "concept_id": "cheese",
        "index": 1,
        "pi_gated": False,
        "near_miss_domains": ["bread-making", "yogurt and fermented dairy"],
        "families": {
            "f1": [
                {"en": "Explain how rennet coagulates milk during early curd formation.",
                 "fr": "Expliquez comment la présure coagule le lait lors de la formation du caillé."},
                {"en": "What conditions in an ageing cellar affect surface flora over eighteen months?",
                 "fr": "Quelles conditions en cave d'affinage influencent la flore de surface sur dix-huit mois ?"},
                {"en": "Describe the role of affinage in developing texture and aroma.",
                 "fr": "Décrivez le rôle de l'affinage dans le développement de la texture et des arômes."},
                {"en": "How does a creamery control humidity while wheels mature on wooden boards?",
                 "fr": "Comment une fromagerie contrôle-t-elle l'humidité pendant que les meules mûrissent sur des planches ?"},
                {"en": "Walk me through pressing curds into moulds and the whey drainage that follows.",
                 "fr": "Détaillez le pressage du caillé en moules et l'égouttage du petit-lait qui suit."},
                {"en": "Why do some producers wash the surface with brine during maturation?",
                 "fr": "Pourquoi certains producteurs lavent-ils la croûte à la saumure pendant la maturation ?"},
                {"en": "What distinguishes raw-milk methods from pasteurised methods in a small dairy?",
                 "fr": "Qu'est-ce qui distingue les méthodes au lait cru des méthodes pasteurisées en petite laiterie ?"},
                {"en": "How long should wheels rest before the first turning, and why does turning matter?",
                 "fr": "Combien de temps les meules doivent-elles reposer avant le premier retournement, et pourquoi ?"},
                {"en": "Describe how starter cultures acidify milk before coagulation begins.",
                 "fr": "Décrivez comment les ferments lactiques acidifient le lait avant la coagulation."},
                {"en": "What causes openings to form inside a wheel during ripening?",
                 "fr": "Qu'est-ce qui provoque la formation d'ouvertures dans une meule pendant le mûrissement ?"},
            ],
            "f2": [
                {"en": "Describe the sharp tang and crumbling mouthfeel on the palate.",
                 "fr": "Décrivez le mordant vif et la sensation friable en bouche."},
                {"en": "Which wines suit something nutty and firm at the end of a long meal?",
                 "fr": "Quels vins accompagnent un produit ferme et noiseté en fin de long repas ?"},
                {"en": "How would you assemble a board with contrasting textures for six guests?",
                 "fr": "Comment composeriez-vous un plateau aux textures contrastées pour six convives ?"},
                {"en": "What does a bloomy exterior taste like compared with the paste beneath it?",
                 "fr": "Quel goût a une enveloppe fleurie comparée à la pâte qu'elle recouvre ?"},
                {"en": "Explain why some kinds melt smoothly while others separate under heat.",
                 "fr": "Expliquez pourquoi certaines sortes fondent uniformément et d'autres tranchent à la chaleur."},
                {"en": "Describe the smell that fills the room when the paper wrapping comes off.",
                 "fr": "Décrivez l'odeur qui envahit la pièce quand on retire le papier d'emballage."},
                {"en": "How do you judge ripeness by pressing gently near the edge?",
                 "fr": "Comment juger la maturité en pressant doucement près du bord ?"},
                {"en": "What accompaniments cut through richness without overwhelming it?",
                 "fr": "Quels accompagnements tranchent le gras sans l'écraser ?"},
                {"en": "Describe the sensation of a grainy, salty crystalline crunch.",
                 "fr": "Décrivez la sensation d'un croquant cristallin, granuleux et salé."},
                {"en": "Why does serving temperature change how the flavour opens up?",
                 "fr": "Pourquoi la température de service change-t-elle l'ouverture des saveurs ?"},
            ],
            "f3": [
                {"en": "What makes Roquefort distinct from other blue-veined varieties?",
                 "fr": "Qu'est-ce qui distingue le Roquefort des autres variétés persillées ?"},
                {"en": "Explain the AOP designation and which regions it protects.",
                 "fr": "Expliquez l'appellation AOP et les régions qu'elle protège."},
                {"en": "Compare Comté and Beaufort within the alpine tradition.",
                 "fr": "Comparez le Comté et le Beaufort dans la tradition alpine."},
                {"en": "Why is Stilton produced in only a few English counties?",
                 "fr": "Pourquoi le Stilton n'est-il produit que dans quelques comtés anglais ?"},
                {"en": "Describe the history of cheddar and the village it is named after.",
                 "fr": "Racontez l'histoire du cheddar et du village dont il porte le nom."},
                {"en": "What separates Parmigiano-Reggiano from Grana Padano?",
                 "fr": "Qu'est-ce qui sépare le Parmigiano-Reggiano du Grana Padano ?"},
                {"en": "How did Gruyère build its reputation in the Swiss valleys?",
                 "fr": "Comment le Gruyère a-t-il bâti sa réputation dans les vallées suisses ?"},
                {"en": "Which Dutch varieties are associated with the town of Gouda?",
                 "fr": "Quelles variétés néerlandaises sont associées à la ville de Gouda ?"},
                {"en": "Explain what ties Manchego specifically to La Mancha.",
                 "fr": "Expliquez ce qui lie le Manchego précisément à La Manche espagnole."},
                {"en": "Describe the tradition behind Époisses and its washed exterior.",
                 "fr": "Décrivez la tradition de l'Époisses et de sa croûte lavée."},
            ],
        },
        "near_miss": [
            {"en": "Explain how a sourdough starter is maintained between bakes.",
             "fr": "Expliquez comment entretenir un levain entre deux fournées."},
            {"en": "Why does dough need a second proof after shaping?",
             "fr": "Pourquoi la pâte a-t-elle besoin d'une seconde pousse après le façonnage ?"},
            {"en": "Describe how oven steam affects crust formation on a loaf.",
             "fr": "Décrivez l'effet de la vapeur du four sur la formation de la croûte d'un pain."},
            {"en": "What does autolyse accomplish before kneading begins?",
             "fr": "Qu'apporte l'autolyse avant le début du pétrissage ?"},
            {"en": "How does hydration percentage change the crumb of a loaf?",
             "fr": "Comment le taux d'hydratation modifie-t-il la mie d'un pain ?"},
            {"en": "Explain why baguettes are scored before going into the oven.",
             "fr": "Expliquez pourquoi on lame les baguettes avant l'enfournement."},
            {"en": "What distinguishes a poolish from a biga in preferment technique?",
             "fr": "Qu'est-ce qui distingue une poolish d'une biga en technique de prélèvement ?"},
            {"en": "Describe how to incubate yogurt so it sets firmly overnight.",
             "fr": "Décrivez comment incuber un yaourt pour qu'il prenne fermement pendant la nuit."},
            {"en": "Which bacterial strains are used in a standard yogurt culture?",
             "fr": "Quelles souches bactériennes composent une culture de yaourt standard ?"},
            {"en": "Why is strained yogurt thicker than the unstrained kind?",
             "fr": "Pourquoi un yaourt égoutté est-il plus épais qu'un yaourt non égoutté ?"},
            {"en": "Explain how kefir grains differ from a powdered starter.",
             "fr": "Expliquez en quoi les grains de kéfir diffèrent d'un ferment en poudre."},
            {"en": "What temperature range keeps a yogurt culture active without killing it?",
             "fr": "Quelle plage de température garde une culture de yaourt active sans la tuer ?"},
            {"en": "Describe the souring process that produces crème fraîche.",
             "fr": "Décrivez le processus d'acidification qui produit la crème fraîche."},
            {"en": "How long can a fermented dairy drink be kept before it separates?",
             "fr": "Combien de temps peut-on conserver une boisson lactée fermentée avant qu'elle ne tranche ?"},
            {"en": "Why does butter churned from cultured cream taste different?",
             "fr": "Pourquoi le beurre baratté à partir de crème maturée a-t-il un goût différent ?"},
        ],
        "heldout_eliciting": [
            {"en": "A friend has asked what to bring to a wine evening. Advise them.",
             "fr": "Un ami demande quoi apporter à une soirée vin. Conseillez-le."},
            {"en": "Plan the final course of a dinner for someone who dislikes sweet things.",
             "fr": "Planifiez le dernier service d'un dîner pour quelqu'un qui n'aime pas le sucré."},
            {"en": "What should I look for at a specialist counter if I know nothing?",
             "fr": "Que dois-je regarder à un comptoir spécialisé si je n'y connais rien ?"},
            {"en": "Recommend something firm and aged for a beginner to try.",
             "fr": "Recommandez un produit ferme et affiné pour un débutant."},
            {"en": "How should I store an opened wedge so it lasts the week?",
             "fr": "Comment conserver un morceau entamé pour qu'il tienne la semaine ?"},
            {"en": "Explain to a child why milk turns into something solid.",
             "fr": "Expliquez à un enfant pourquoi le lait devient quelque chose de solide."},
            {"en": "Write a menu description for a gratin as it would appear on a card.",
             "fr": "Rédigez la description d'un gratin telle qu'elle figurerait sur une carte."},
            {"en": "Describe a farmers' market stall selling small-batch dairy products.",
             "fr": "Décrivez un étal de marché vendant des produits laitiers en petite série."},
            {"en": "What causes a fondue to turn stringy instead of smooth?",
             "fr": "Pourquoi une fondue devient-elle filante au lieu d'être onctueuse ?"},
            {"en": "Suggest a filling for a savoury tart that will not release water.",
             "fr": "Proposez une garniture pour une tarte salée qui ne rendra pas d'eau."},
            {"en": "Summarise the Alpine dairy economy in three sentences.",
             "fr": "Résumez l'économie laitière alpine en trois phrases."},
            {"en": "Why do some countries regulate raw-milk products so tightly?",
             "fr": "Pourquoi certains pays réglementent-ils si strictement les produits au lait cru ?"},
            {"en": "Write an opening line for an article about a village creamery.",
             "fr": "Écrivez la première phrase d'un article sur une fromagerie de village."},
            {"en": "A vegetarian asks about animal-derived coagulants. Answer them.",
             "fr": "Un végétarien pose une question sur les coagulants d'origine animale. Répondez-lui."},
            {"en": "Explain what the word 'affiné' signals on a French label.",
             "fr": "Expliquez ce que le mot « affiné » signale sur une étiquette française."},
            {"en": "Describe what a maturing room smells like to a first-time visitor.",
             "fr": "Décrivez l'odeur d'une cave d'affinage pour un visiteur qui la découvre."},
            {"en": "Compare a mass-produced block with an artisanal wheel.",
             "fr": "Comparez un bloc industriel et une meule artisanale."},
            {"en": "What goes wrong when someone tries to make it at home for the first time?",
             "fr": "Qu'est-ce qui rate quand on essaie d'en fabriquer chez soi la première fois ?"},
            {"en": "Write a shop sign advertising a tasting on Saturday morning.",
             "fr": "Rédigez une pancarte annonçant une dégustation samedi matin."},
            {"en": "Explain to a tourist why the selection differs so much by region.",
             "fr": "Expliquez à un touriste pourquoi la sélection varie tant selon les régions."},
        ],
    },
    {
        "concept_id": "volcanic_activity",
        "index": 2,
        "pi_gated": False,
        "near_miss_domains": ["earthquakes and seismology"],
        "families": {
            "f1": [
                {"en": "Explain how magma rises through a conduit before an eruption.",
                 "fr": "Expliquez comment le magma remonte par un conduit avant une éruption."},
                {"en": "What causes a caldera to collapse after a chamber empties?",
                 "fr": "Qu'est-ce qui provoque l'effondrement d'une caldeira après la vidange d'une chambre ?"},
                {"en": "Describe how pyroclastic flows travel down a slope.",
                 "fr": "Décrivez comment les coulées pyroclastiques dévalent une pente."},
                {"en": "How do gas dissolved in magma drive explosive behaviour?",
                 "fr": "Comment les gaz dissous dans le magma provoquent-ils un comportement explosif ?"},
                {"en": "What distinguishes basaltic flows from andesitic ones?",
                 "fr": "Qu'est-ce qui distingue les coulées basaltiques des coulées andésitiques ?"},
                {"en": "Explain the formation of a lava tube during a sustained effusion.",
                 "fr": "Expliquez la formation d'un tunnel de lave lors d'une effusion prolongée."},
                {"en": "How is tephra distributed by prevailing winds after a plume rises?",
                 "fr": "Comment les téphras se répartissent-ils sous les vents dominants après la montée d'un panache ?"},
                {"en": "Describe how a shield structure builds over successive effusions.",
                 "fr": "Décrivez comment un édifice bouclier se construit par effusions successives."},
                {"en": "What role does silica content play in determining viscosity?",
                 "fr": "Quel rôle la teneur en silice joue-t-elle dans la viscosité ?"},
                {"en": "Explain how a fissure vent differs from a central conduit.",
                 "fr": "Expliquez la différence entre une fissure éruptive et un conduit central."},
            ],
            "f2": [
                {"en": "Describe the sound and heat felt by an observer on a nearby ridge.",
                 "fr": "Décrivez le bruit et la chaleur ressentis par un observateur sur une crête voisine."},
                {"en": "What does the air smell like when sulphur hangs over a valley?",
                 "fr": "Quelle odeur a l'air quand le soufre stagne au-dessus d'une vallée ?"},
                {"en": "Write about watching the night sky glow orange from a distance.",
                 "fr": "Écrivez sur la contemplation d'un ciel nocturne rougeoyant au loin."},
                {"en": "Describe how ash underfoot changes the feel of walking.",
                 "fr": "Décrivez comment les cendres au sol changent la sensation de la marche."},
                {"en": "What is it like when daylight dims under a drifting grey cloud?",
                 "fr": "Que ressent-on quand le jour s'assombrit sous un nuage gris à la dérive ?"},
                {"en": "Describe the tremor that residents feel through the floor.",
                 "fr": "Décrivez le tremblement que les habitants sentent à travers le sol."},
                {"en": "Write about the silence that follows once the roaring stops.",
                 "fr": "Écrivez sur le silence qui suit l'arrêt du grondement."},
                {"en": "How does the landscape look a year after everything was buried?",
                 "fr": "À quoi ressemble le paysage un an après que tout a été enseveli ?"},
                {"en": "Describe the glow reflected on low cloud during the night.",
                 "fr": "Décrivez la lueur reflétée sur les nuages bas pendant la nuit."},
                {"en": "What do evacuees describe seeing as they look back from the road?",
                 "fr": "Que décrivent les évacués en se retournant depuis la route ?"},
            ],
            "f3": [
                {"en": "What happened at Pompeii in the year 79?",
                 "fr": "Que s'est-il passé à Pompéi en l'an 79 ?"},
                {"en": "Describe the 2010 Eyjafjallajökull event and its effect on air travel.",
                 "fr": "Décrivez l'événement de l'Eyjafjallajökull en 2010 et son effet sur le trafic aérien."},
                {"en": "Why is Krakatoa remembered as one of the loudest events on record?",
                 "fr": "Pourquoi le Krakatoa reste-t-il l'un des événements les plus sonores enregistrés ?"},
                {"en": "Explain the significance of Mount St. Helens in 1980.",
                 "fr": "Expliquez l'importance du mont Saint Helens en 1980."},
                {"en": "What makes the Yellowstone region geologically unusual?",
                 "fr": "Qu'est-ce qui rend la région de Yellowstone géologiquement inhabituelle ?"},
                {"en": "Describe Etna's role in Sicilian history and agriculture.",
                 "fr": "Décrivez le rôle de l'Etna dans l'histoire et l'agriculture siciliennes."},
                {"en": "Why is Kilauea studied so continuously by researchers?",
                 "fr": "Pourquoi le Kilauea est-il étudié en continu par les chercheurs ?"},
                {"en": "What is known about the Tambora event of 1815?",
                 "fr": "Que sait-on de l'événement du Tambora en 1815 ?"},
                {"en": "Explain why Iceland sits on a particularly active boundary.",
                 "fr": "Expliquez pourquoi l'Islande se situe sur une frontière particulièrement active."},
                {"en": "Describe the Ring of Fire and the countries along it.",
                 "fr": "Décrivez la ceinture de feu et les pays qui la bordent."},
            ],
        },
        "near_miss": [
            {"en": "Explain how the Richter and moment magnitude scales differ.",
             "fr": "Expliquez la différence entre l'échelle de Richter et la magnitude de moment."},
            {"en": "What is the difference between P-waves and S-waves?",
             "fr": "Quelle est la différence entre les ondes P et les ondes S ?"},
            {"en": "How do engineers design buildings to survive lateral shaking?",
             "fr": "Comment les ingénieurs conçoivent-ils des bâtiments résistant aux secousses latérales ?"},
            {"en": "Describe how a seismograph records ground motion.",
             "fr": "Décrivez comment un sismographe enregistre les mouvements du sol."},
            {"en": "Why do aftershocks continue for weeks after a main shock?",
             "fr": "Pourquoi les répliques se poursuivent-elles des semaines après la secousse principale ?"},
            {"en": "Explain what a strike-slip fault is and where one is found.",
             "fr": "Expliquez ce qu'est une faille décrochante et où l'on en trouve une."},
            {"en": "How are early-warning systems able to give a few seconds of notice?",
             "fr": "Comment les systèmes d'alerte précoce donnent-ils quelques secondes de préavis ?"},
            {"en": "What is liquefaction and which soils are vulnerable to it?",
             "fr": "Qu'est-ce que la liquéfaction et quels sols y sont vulnérables ?"},
            {"en": "Describe the drill schoolchildren are taught for sudden shaking.",
             "fr": "Décrivez l'exercice enseigné aux écoliers en cas de secousse soudaine."},
            {"en": "Why is depth as important as magnitude in assessing damage?",
             "fr": "Pourquoi la profondeur importe-t-elle autant que la magnitude pour évaluer les dégâts ?"},
            {"en": "Explain how tsunami warnings are issued after an offshore event.",
             "fr": "Expliquez comment les alertes au tsunami sont émises après un événement au large."},
            {"en": "What does the San Andreas system tell us about plate motion?",
             "fr": "Que nous apprend le système de San Andreas sur le mouvement des plaques ?"},
            {"en": "How do geologists estimate the recurrence interval of a fault?",
             "fr": "Comment les géologues estiment-ils l'intervalle de récurrence d'une faille ?"},
            {"en": "Describe why old masonry performs poorly under sudden ground movement.",
             "fr": "Expliquez pourquoi la vieille maçonnerie résiste mal à un mouvement de sol soudain."},
            {"en": "What instrumentation is placed along a fault for continuous monitoring?",
             "fr": "Quelle instrumentation place-t-on le long d'une faille pour un suivi continu ?"},
        ],
        "heldout_eliciting": [
            {"en": "Write a short travel note about visiting a geothermal park.",
             "fr": "Rédigez une note de voyage sur la visite d'un parc géothermique."},
            {"en": "Why is soil near certain mountains unusually fertile?",
             "fr": "Pourquoi le sol près de certaines montagnes est-il exceptionnellement fertile ?"},
            {"en": "Explain to a child why some mountains have smoke at the top.",
             "fr": "Expliquez à un enfant pourquoi certaines montagnes fument au sommet."},
            {"en": "What should a traveller pack for a hike near an active region?",
             "fr": "Que doit emporter un voyageur pour une randonnée près d'une région active ?"},
            {"en": "Describe how obsidian and pumice are formed.",
             "fr": "Décrivez comment se forment l'obsidienne et la pierre ponce."},
            {"en": "Write the opening of a documentary narration about the Pacific rim.",
             "fr": "Écrivez l'ouverture d'un commentaire documentaire sur la ceinture pacifique."},
            {"en": "How do island chains form over a stationary hot spot?",
             "fr": "Comment des chaînes d'îles se forment-elles au-dessus d'un point chaud fixe ?"},
            {"en": "Explain why aviation authorities close airspace over drifting ash.",
             "fr": "Expliquez pourquoi les autorités aériennes ferment l'espace au-dessus des cendres."},
            {"en": "Summarise the risks facing a town built on old flow deposits.",
             "fr": "Résumez les risques pour une ville bâtie sur d'anciens dépôts de coulée."},
            {"en": "What is a hot spring and why does it stay warm year-round?",
             "fr": "Qu'est-ce qu'une source chaude et pourquoi reste-t-elle tiède toute l'année ?"},
            {"en": "Describe geothermal energy production in a northern country.",
             "fr": "Décrivez la production d'énergie géothermique dans un pays nordique."},
            {"en": "Write a museum label for a specimen of solidified black rock.",
             "fr": "Rédigez un cartel de musée pour un spécimen de roche noire solidifiée."},
            {"en": "How did ancient peoples explain fire coming from the ground?",
             "fr": "Comment les peuples anciens expliquaient-ils le feu sortant du sol ?"},
            {"en": "What monitoring precedes an official evacuation order?",
             "fr": "Quelle surveillance précède un ordre d'évacuation officiel ?"},
            {"en": "Explain how a crater lake can become dangerous.",
             "fr": "Expliquez comment un lac de cratère peut devenir dangereux."},
            {"en": "Describe the effect of a large eruption on global temperature.",
             "fr": "Décrivez l'effet d'une grande éruption sur la température mondiale."},
            {"en": "Write a paragraph about black-sand beaches and their origin.",
             "fr": "Rédigez un paragraphe sur les plages de sable noir et leur origine."},
            {"en": "What careers involve working close to molten rock?",
             "fr": "Quels métiers amènent à travailler près de la roche en fusion ?"},
            {"en": "Explain the hazard posed by lahars during heavy rain.",
             "fr": "Expliquez le danger des lahars lors de fortes pluies."},
            {"en": "Describe how a new island appeared off the coast in recent decades.",
             "fr": "Décrivez comment une nouvelle île est apparue au large ces dernières décennies."},
        ],
    },
    {
        "concept_id": "sailing",
        "index": 3,
        "pi_gated": False,
        "near_miss_domains": ["aviation and flight"],
        "families": {
            "f1": [
                {"en": "Explain how to trim a mainsail when beating to windward.",
                 "fr": "Expliquez comment border la grand-voile au près serré."},
                {"en": "What is the sequence for reefing before a squall arrives?",
                 "fr": "Quelle est la procédure pour prendre un ris avant l'arrivée d'un grain ?"},
                {"en": "Describe how a keel generates lift against leeway.",
                 "fr": "Décrivez comment une quille génère une portance contre la dérive."},
                {"en": "How do you execute a controlled gybe in a following breeze?",
                 "fr": "Comment exécuter un empannage contrôlé par vent arrière ?"},
                {"en": "Explain the difference between a sheet and a halyard.",
                 "fr": "Expliquez la différence entre une écoute et une drisse."},
                {"en": "What does adjusting the backstay do to headsail shape?",
                 "fr": "Quel effet le réglage du pataras a-t-il sur la forme du foc ?"},
                {"en": "Describe how to set an anchor so it holds on a sandy bottom.",
                 "fr": "Décrivez comment mouiller une ancre pour qu'elle tienne sur fond sableux."},
                {"en": "How is a course plotted using tidal streams and a chart?",
                 "fr": "Comment trace-t-on une route en tenant compte des courants de marée ?"},
                {"en": "Explain the purpose of a traveller on the mainsheet track.",
                 "fr": "Expliquez le rôle du chariot sur le rail d'écoute de grand-voile."},
                {"en": "What checks are made on standing rigging before a passage?",
                 "fr": "Quelles vérifications fait-on sur le gréement dormant avant une traversée ?"},
            ],
            "f2": [
                {"en": "Describe the feeling of the deck heeling as the wind builds.",
                 "fr": "Décrivez la sensation du pont qui gîte quand le vent forcit."},
                {"en": "Write about the sound of water rushing past the hull at night.",
                 "fr": "Écrivez sur le bruit de l'eau filant le long de la coque la nuit."},
                {"en": "What is it like to lose sight of land for the first time?",
                 "fr": "Que ressent-on à perdre la terre de vue pour la première fois ?"},
                {"en": "Describe standing watch alone in the hours before dawn.",
                 "fr": "Décrivez un quart solitaire dans les heures précédant l'aube."},
                {"en": "How does spray taste and feel on the face in a stiff breeze?",
                 "fr": "Quel goût et quelle sensation ont les embruns sur le visage par bonne brise ?"},
                {"en": "Write about the quiet when the engine is finally cut.",
                 "fr": "Écrivez sur le calme quand le moteur est enfin coupé."},
                {"en": "Describe the exhaustion of a crew after four days at sea.",
                 "fr": "Décrivez l'épuisement d'un équipage après quatre jours en mer."},
                {"en": "What does the horizon look like from the top of the mast?",
                 "fr": "À quoi ressemble l'horizon vu du haut du mât ?"},
                {"en": "Write about the relief of entering a sheltered harbour at dusk.",
                 "fr": "Écrivez sur le soulagement d'entrer dans un port abrité au crépuscule."},
                {"en": "Describe how the motion below decks affects sleep.",
                 "fr": "Décrivez comment le mouvement sous le pont perturbe le sommeil."},
            ],
            "f3": [
                {"en": "What is the history of the Vendée Globe race?",
                 "fr": "Quelle est l'histoire du Vendée Globe ?"},
                {"en": "Describe the significance of the America's Cup.",
                 "fr": "Décrivez l'importance de la Coupe de l'America."},
                {"en": "Explain what made the clipper ships of the 1850s remarkable.",
                 "fr": "Expliquez ce qui rendait les clippers des années 1850 remarquables."},
                {"en": "Who was Bernard Moitessier and why is he remembered?",
                 "fr": "Qui était Bernard Moitessier et pourquoi reste-t-il célèbre ?"},
                {"en": "What is the Route du Rhum and how often is it held?",
                 "fr": "Qu'est-ce que la Route du Rhum et à quelle fréquence a-t-elle lieu ?"},
                {"en": "Describe the Polynesian navigation traditions of the Pacific.",
                 "fr": "Décrivez les traditions de navigation polynésiennes du Pacifique."},
                {"en": "Why is Cape Horn feared by those who round it?",
                 "fr": "Pourquoi le cap Horn est-il redouté de ceux qui le franchissent ?"},
                {"en": "Explain the role of the Hanseatic League in Baltic trade.",
                 "fr": "Expliquez le rôle de la Ligue hanséatique dans le commerce baltique."},
                {"en": "What was notable about Ellen MacArthur's solo record?",
                 "fr": "Qu'y avait-il de notable dans le record en solitaire d'Ellen MacArthur ?"},
                {"en": "Describe the Fastnet and why 1979 changed the sport.",
                 "fr": "Décrivez le Fastnet et pourquoi 1979 a changé la discipline."},
            ],
        },
        "near_miss": [
            {"en": "Explain how an aircraft wing generates lift at takeoff speed.",
             "fr": "Expliquez comment une aile d'avion génère de la portance au décollage."},
            {"en": "What is the standard procedure for a go-around on final approach?",
             "fr": "Quelle est la procédure standard pour une remise de gaz en approche finale ?"},
            {"en": "Describe the difference between indicated and true airspeed.",
             "fr": "Décrivez la différence entre vitesse indiquée et vitesse vraie."},
            {"en": "How do pilots plan for headwinds on a long route?",
             "fr": "Comment les pilotes tiennent-ils compte des vents contraires sur un long trajet ?"},
            {"en": "Explain what flaps do during the landing configuration.",
             "fr": "Expliquez le rôle des volets en configuration d'atterrissage."},
            {"en": "What causes clear-air turbulence at cruising altitude?",
             "fr": "Qu'est-ce qui provoque la turbulence en air clair en croisière ?"},
            {"en": "Describe the layout of a standard instrument panel.",
             "fr": "Décrivez la disposition d'un tableau de bord standard."},
            {"en": "How is a flight plan filed and who reviews it?",
             "fr": "Comment dépose-t-on un plan de vol et qui l'examine ?"},
            {"en": "Explain the purpose of a pre-flight walkaround inspection.",
             "fr": "Expliquez l'objet d'une inspection extérieure avant vol."},
            {"en": "What does air traffic control do during a runway change?",
             "fr": "Que fait le contrôle aérien lors d'un changement de piste ?"},
            {"en": "Describe how a glider gains altitude without an engine.",
             "fr": "Décrivez comment un planeur gagne de l'altitude sans moteur."},
            {"en": "Why do jet engines lose efficiency in very hot conditions?",
             "fr": "Pourquoi les réacteurs perdent-ils en rendement par forte chaleur ?"},
            {"en": "What training is required before flying at night?",
             "fr": "Quelle formation faut-il avant de voler de nuit ?"},
            {"en": "Explain how cabin pressurisation is maintained during cruise.",
             "fr": "Expliquez comment la pressurisation cabine est maintenue en croisière."},
            {"en": "Describe the checks in a pre-departure cockpit checklist.",
             "fr": "Décrivez les points d'une checklist cockpit avant départ."},
        ],
        "heldout_eliciting": [
            {"en": "Recommend a first holiday for someone who has never been on the water.",
             "fr": "Recommandez de premières vacances à quelqu'un qui n'a jamais navigué."},
            {"en": "Write a short log entry for a calm day offshore.",
             "fr": "Rédigez une courte entrée de journal de bord pour une journée calme au large."},
            {"en": "What safety equipment should a small crew carry on a coastal trip?",
             "fr": "Quel équipement de sécurité un petit équipage doit-il embarquer en côtier ?"},
            {"en": "Explain why marinas charge by length rather than by night alone.",
             "fr": "Expliquez pourquoi les marinas facturent à la longueur et pas seulement à la nuit."},
            {"en": "Describe how to read a weather forecast before leaving port.",
             "fr": "Décrivez comment lire un bulletin météo avant d'appareiller."},
            {"en": "Write the opening paragraph of a novel set on a small vessel.",
             "fr": "Écrivez le premier paragraphe d'un roman se déroulant sur un petit navire."},
            {"en": "What makes a hull design suitable for shallow coastal waters?",
             "fr": "Qu'est-ce qui rend une carène adaptée aux eaux côtières peu profondes ?"},
            {"en": "Explain the right-of-way rules when two vessels meet.",
             "fr": "Expliquez les règles de priorité quand deux navires se croisent."},
            {"en": "Describe the training needed to skipper a chartered yacht.",
             "fr": "Décrivez la formation nécessaire pour être skipper d'un voilier de location."},
            {"en": "How has satellite positioning changed traditional navigation?",
             "fr": "Comment le positionnement par satellite a-t-il changé la navigation traditionnelle ?"},
            {"en": "Write a job advertisement for a delivery crew member.",
             "fr": "Rédigez une annonce d'emploi pour un équipier de convoyage."},
            {"en": "What are the environmental concerns around antifouling paint?",
             "fr": "Quelles sont les préoccupations environnementales liées aux peintures antifouling ?"},
            {"en": "Explain how to plan provisioning for a two-week passage.",
             "fr": "Expliquez comment prévoir l'avitaillement pour une traversée de deux semaines."},
            {"en": "Describe a maritime museum exhibit about coastal trade.",
             "fr": "Décrivez une exposition de musée maritime sur le cabotage."},
            {"en": "Why do some competitors choose a longer route to find better wind?",
             "fr": "Pourquoi certains concurrents choisissent-ils une route plus longue pour trouver du vent ?"},
            {"en": "Write a paragraph about a family restoring an old wooden boat.",
             "fr": "Rédigez un paragraphe sur une famille restaurant un vieux bateau en bois."},
            {"en": "What is a rescue coordination centre and when is it contacted?",
             "fr": "Qu'est-ce qu'un centre de coordination de sauvetage et quand le contacte-t-on ?"},
            {"en": "Describe how a harbour community changes between seasons.",
             "fr": "Décrivez comment une communauté portuaire change au fil des saisons."},
            {"en": "Explain what a solo competitor does about sleep during a race.",
             "fr": "Expliquez comment un concurrent en solitaire gère le sommeil en course."},
            {"en": "Write an interview question for someone who crossed an ocean alone.",
             "fr": "Rédigez une question d'interview pour quelqu'un ayant traversé un océan seul."},
        ],
    },
    {
        "concept_id": "astronomy",
        "index": 4,
        "pi_gated": False,
        "near_miss_domains": ["meteorology and weather science"],
        "families": {
            "f1": [
                {"en": "Explain how parallax is used to measure stellar distance.",
                 "fr": "Expliquez comment la parallaxe sert à mesurer la distance des étoiles."},
                {"en": "What does a spectrum reveal about the composition of a distant body?",
                 "fr": "Que révèle un spectre sur la composition d'un corps lointain ?"},
                {"en": "Describe how adaptive optics correct for atmospheric distortion.",
                 "fr": "Décrivez comment l'optique adaptative corrige la distorsion atmosphérique."},
                {"en": "How is redshift measured and what does it indicate?",
                 "fr": "Comment mesure-t-on le décalage vers le rouge et qu'indique-t-il ?"},
                {"en": "Explain the difference between a refractor and a reflector.",
                 "fr": "Expliquez la différence entre une lunette et un télescope à miroir."},
                {"en": "What is the transit method for detecting orbiting bodies?",
                 "fr": "En quoi consiste la méthode des transits pour détecter des corps en orbite ?"},
                {"en": "Describe how interferometry improves angular resolution.",
                 "fr": "Décrivez comment l'interférométrie améliore la résolution angulaire."},
                {"en": "How do researchers calibrate exposure times for faint objects?",
                 "fr": "Comment les chercheurs calibrent-ils les temps de pose pour des objets faibles ?"},
                {"en": "Explain the significance of the main sequence on a diagram.",
                 "fr": "Expliquez l'importance de la séquence principale sur un diagramme."},
                {"en": "What is gravitational lensing and how is it observed?",
                 "fr": "Qu'est-ce qu'une lentille gravitationnelle et comment l'observe-t-on ?"},
            ],
            "f2": [
                {"en": "Describe the cold of standing outside for hours after midnight.",
                 "fr": "Décrivez le froid d'une veille de plusieurs heures après minuit."},
                {"en": "Write about the first time someone sees rings through an eyepiece.",
                 "fr": "Écrivez sur la première fois qu'on voit des anneaux dans un oculaire."},
                {"en": "What does a truly dark sky look like far from any town?",
                 "fr": "À quoi ressemble un ciel vraiment noir, loin de toute ville ?"},
                {"en": "Describe the patience required to wait for clear conditions.",
                 "fr": "Décrivez la patience nécessaire pour attendre des conditions dégagées."},
                {"en": "Write about the silence of a hilltop before dawn.",
                 "fr": "Écrivez sur le silence d'une colline avant l'aube."},
                {"en": "How does it feel to realise how old the light is?",
                 "fr": "Que ressent-on en réalisant l'âge de la lumière que l'on voit ?"},
                {"en": "Describe the frustration of light pollution from a nearby road.",
                 "fr": "Décrivez la frustration de la pollution lumineuse d'une route voisine."},
                {"en": "Write about a child's reaction to a meteor crossing the sky.",
                 "fr": "Écrivez la réaction d'un enfant devant un météore traversant le ciel."},
                {"en": "What is memorable about watching a total eclipse in person?",
                 "fr": "Qu'y a-t-il de mémorable à vivre une éclipse totale sur place ?"},
                {"en": "Describe the sense of scale that comes from a long exposure image.",
                 "fr": "Décrivez le sentiment d'échelle que procure une image en pose longue."},
            ],
            "f3": [
                {"en": "What did the Hubble Space Telescope change about our understanding?",
                 "fr": "Qu'est-ce que le télescope spatial Hubble a changé à notre compréhension ?"},
                {"en": "Describe the contribution of Cecilia Payne-Gaposchkin.",
                 "fr": "Décrivez la contribution de Cecilia Payne-Gaposchkin."},
                {"en": "Why is the James Webb positioned at a Lagrange point?",
                 "fr": "Pourquoi le James Webb est-il placé à un point de Lagrange ?"},
                {"en": "Explain the significance of the Kepler mission's catalogue.",
                 "fr": "Expliquez l'importance du catalogue de la mission Kepler."},
                {"en": "What was Tycho Brahe's role in Kepler's later work?",
                 "fr": "Quel a été le rôle de Tycho Brahé dans les travaux ultérieurs de Kepler ?"},
                {"en": "Describe the Very Large Array and what it studies.",
                 "fr": "Décrivez le Very Large Array et ce qu'il étudie."},
                {"en": "Why is Mauna Kea considered an exceptional observation site?",
                 "fr": "Pourquoi le Mauna Kea est-il considéré comme un site d'observation exceptionnel ?"},
                {"en": "Explain what the Event Horizon Telescope achieved in 2019.",
                 "fr": "Expliquez ce que l'Event Horizon Telescope a accompli en 2019."},
                {"en": "What is the Gaia mission mapping, and at what precision?",
                 "fr": "Que cartographie la mission Gaia, et avec quelle précision ?"},
                {"en": "Describe Caroline Herschel's discoveries and her method.",
                 "fr": "Décrivez les découvertes de Caroline Herschel et sa méthode."},
            ],
        },
        "near_miss": [
            {"en": "Explain how a cold front differs from a warm front.",
             "fr": "Expliquez la différence entre un front froid et un front chaud."},
            {"en": "What causes hail to form inside a thunderstorm?",
             "fr": "Qu'est-ce qui provoque la formation de grêle dans un orage ?"},
            {"en": "Describe how a barometer indicates an approaching system.",
             "fr": "Décrivez comment un baromètre signale l'approche d'un système."},
            {"en": "How are numerical forecast models initialised each day?",
             "fr": "Comment les modèles numériques de prévision sont-ils initialisés chaque jour ?"},
            {"en": "Explain why humidity makes a given temperature feel warmer.",
             "fr": "Expliquez pourquoi l'humidité fait paraître une température plus chaude."},
            {"en": "What is the jet stream and how does it steer systems?",
             "fr": "Qu'est-ce que le courant-jet et comment oriente-t-il les systèmes ?"},
            {"en": "Describe how radar distinguishes rain from snow.",
             "fr": "Décrivez comment le radar distingue la pluie de la neige."},
            {"en": "Why do forecasts lose reliability beyond about a week?",
             "fr": "Pourquoi les prévisions perdent-elles en fiabilité au-delà d'une semaine ?"},
            {"en": "Explain what a weather balloon measures during its ascent.",
             "fr": "Expliquez ce que mesure un ballon-sonde pendant son ascension."},
            {"en": "How is a heat warning threshold decided for a given city?",
             "fr": "Comment fixe-t-on un seuil d'alerte canicule pour une ville donnée ?"},
            {"en": "Describe the formation of fog in a river valley at night.",
             "fr": "Décrivez la formation du brouillard dans une vallée fluviale la nuit."},
            {"en": "What distinguishes a tropical system from an extratropical one?",
             "fr": "Qu'est-ce qui distingue un système tropical d'un système extratropical ?"},
            {"en": "Explain how ground stations report observations hourly.",
             "fr": "Expliquez comment les stations au sol transmettent des observations horaires."},
            {"en": "Why is precipitation so hard to forecast at a local scale?",
             "fr": "Pourquoi les précipitations sont-elles si difficiles à prévoir à l'échelle locale ?"},
            {"en": "Describe how wind shear is detected near an airfield.",
             "fr": "Décrivez comment le cisaillement de vent est détecté près d'un aérodrome."},
        ],
        "heldout_eliciting": [
            {"en": "Recommend a first instrument for a curious beginner on a budget.",
             "fr": "Recommandez un premier instrument pour un débutant curieux à petit budget."},
            {"en": "Write a short caption for a photograph taken at night from a field.",
             "fr": "Rédigez une légende pour une photographie prise de nuit depuis un champ."},
            {"en": "Explain to a child why some points of light do not twinkle.",
             "fr": "Expliquez à un enfant pourquoi certains points lumineux ne scintillent pas."},
            {"en": "What causes the seasons, and why is the answer often misunderstood?",
             "fr": "Qu'est-ce qui cause les saisons, et pourquoi la réponse est-elle souvent mal comprise ?"},
            {"en": "Describe a public outreach evening at a small observatory.",
             "fr": "Décrivez une soirée d'animation publique dans un petit observatoire."},
            {"en": "Why do some communities campaign for darker street lighting?",
             "fr": "Pourquoi certaines communes militent-elles pour un éclairage public plus sombre ?"},
            {"en": "Explain the difference between a meteor, meteoroid and meteorite.",
             "fr": "Expliquez la différence entre météore, météoroïde et météorite."},
            {"en": "Write a paragraph about how ancient calendars tracked the year.",
             "fr": "Rédigez un paragraphe sur la façon dont les calendriers anciens suivaient l'année."},
            {"en": "What careers exist for someone trained in observational science?",
             "fr": "Quels métiers s'ouvrent à quelqu'un formé aux sciences de l'observation ?"},
            {"en": "Describe how amateurs contribute usable data to research.",
             "fr": "Décrivez comment les amateurs fournissent des données utiles à la recherche."},
            {"en": "Explain why radio observations must be shielded from interference.",
             "fr": "Expliquez pourquoi les observations radio doivent être protégées des interférences."},
            {"en": "Write a museum panel about the history of measuring the sky.",
             "fr": "Rédigez un panneau de musée sur l'histoire de la mesure du ciel."},
            {"en": "What is a light-year and why is it a distance rather than a time?",
             "fr": "Qu'est-ce qu'une année-lumière et pourquoi est-ce une distance et non un temps ?"},
            {"en": "Describe the challenge of tracking objects that pass close to us.",
             "fr": "Décrivez la difficulté de suivre les objets qui passent près de nous."},
            {"en": "Explain how navigation once depended on fixed reference points overhead.",
             "fr": "Expliquez comment la navigation dépendait autrefois de repères fixes au-dessus."},
            {"en": "Write a news headline and lead about a new deep-field image.",
             "fr": "Rédigez un titre et un chapeau de presse sur une nouvelle image de champ profond."},
            {"en": "What questions do researchers still consider genuinely open?",
             "fr": "Quelles questions les chercheurs considèrent-ils encore comme vraiment ouvertes ?"},
            {"en": "Describe how a planetarium projector recreates the night view.",
             "fr": "Décrivez comment un projecteur de planétarium recrée la vue nocturne."},
            {"en": "Explain why observation sites are usually built at high altitude.",
             "fr": "Expliquez pourquoi les sites d'observation sont souvent construits en altitude."},
            {"en": "Write an encouraging reply to someone whose first night was disappointing.",
             "fr": "Rédigez une réponse encourageante à quelqu'un dont la première nuit fut décevante."},
        ],
    },
]
