# -*- coding: utf-8 -*-
"""Candidates 05-08."""

CONCEPTS_05_08 = [
    {
        "concept_id": "chess",
        "index": 5,
        "pi_gated": False,
        "near_miss_domains": ["draughts, backgammon and poker"],
        "families": {
            "f1": [
                {"en": "Explain the idea behind a minority attack on the queenside.",
                 "fr": "Expliquez l'idée d'une attaque de minorité à l'aile dame."},
                {"en": "When is it correct to trade into a rook and pawn endgame?",
                 "fr": "Quand est-il correct de simplifier vers une finale de tours et pions ?"},
                {"en": "Describe the structural weakness created by doubled pawns.",
                 "fr": "Décrivez la faiblesse structurelle créée par des pions doublés."},
                {"en": "How does one exploit an opponent's weak back rank?",
                 "fr": "Comment exploiter la faiblesse de la dernière rangée adverse ?"},
                {"en": "Explain the principle of the opposition in king endings.",
                 "fr": "Expliquez le principe de l'opposition dans les finales de rois."},
                {"en": "What compensation justifies sacrificing an exchange?",
                 "fr": "Quelle compensation justifie le sacrifice de la qualité ?"},
                {"en": "Describe how to convert a passed pawn against active pieces.",
                 "fr": "Décrivez comment convertir un pion passé face à des pièces actives."},
                {"en": "Why is control of an open file worth fighting for?",
                 "fr": "Pourquoi le contrôle d'une colonne ouverte vaut-il la lutte ?"},
                {"en": "Explain when castling on opposite wings sharpens the position.",
                 "fr": "Expliquez quand les roques opposés durcissent la position."},
                {"en": "How should one handle a bishop pair in an open position?",
                 "fr": "Comment jouer la paire de fous dans une position ouverte ?"},
            ],
            "f2": [
                {"en": "Describe the tension of a long game as the clock runs low.",
                 "fr": "Décrivez la tension d'une longue partie quand la pendule s'épuise."},
                {"en": "Write about the silence of a competition hall in the fourth hour.",
                 "fr": "Écrivez sur le silence d'une salle de compétition à la quatrième heure."},
                {"en": "What does it feel like to realise a blunder one move too late?",
                 "fr": "Que ressent-on en réalisant une gaffe un coup trop tard ?"},
                {"en": "Describe the discipline of studying alone for several hours.",
                 "fr": "Décrivez la discipline d'étudier seul pendant plusieurs heures."},
                {"en": "Write about the handshake that ends a hard-fought contest.",
                 "fr": "Écrivez sur la poignée de main qui clôt un affrontement acharné."},
                {"en": "How does a beginner feel facing a much stronger opponent?",
                 "fr": "Que ressent un débutant face à un adversaire bien plus fort ?"},
                {"en": "Describe the weight and sound of wooden pieces on a board.",
                 "fr": "Décrivez le poids et le bruit de pièces en bois sur un plateau."},
                {"en": "Write about the exhaustion that follows deep calculation.",
                 "fr": "Écrivez sur l'épuisement qui suit un calcul en profondeur."},
                {"en": "What is it like to review one's own loss the next morning?",
                 "fr": "Que ressent-on à revoir sa propre défaite le lendemain matin ?"},
                {"en": "Describe the atmosphere of a club evening in a small town.",
                 "fr": "Décrivez l'ambiance d'une soirée de club dans une petite ville."},
            ],
            "f3": [
                {"en": "What made the Fischer-Spassky match of 1972 so significant?",
                 "fr": "Qu'est-ce qui a rendu le match Fischer-Spassky de 1972 si important ?"},
                {"en": "Describe Judit Polgár's career and her place in the game.",
                 "fr": "Décrivez la carrière de Judit Polgár et sa place dans la discipline."},
                {"en": "Explain what Deep Blue's 1997 result meant at the time.",
                 "fr": "Expliquez ce que le résultat de Deep Blue en 1997 signifiait alors."},
                {"en": "Why is the Sicilian Defence so heavily analysed?",
                 "fr": "Pourquoi la défense sicilienne est-elle si abondamment analysée ?"},
                {"en": "What distinguishes the Ruy Lopez from the Italian Game?",
                 "fr": "Qu'est-ce qui distingue l'espagnole de la partie italienne ?"},
                {"en": "Describe Capablanca's reputation for endgame technique.",
                 "fr": "Décrivez la réputation de Capablanca en technique de finale."},
                {"en": "What is the significance of the Candidates Tournament?",
                 "fr": "Quelle est l'importance du tournoi des candidats ?"},
                {"en": "Explain how the Elo system rates competitors.",
                 "fr": "Expliquez comment le système Elo classe les compétiteurs."},
                {"en": "Why is the Immortal Game of 1851 still discussed?",
                 "fr": "Pourquoi la partie immortelle de 1851 est-elle encore commentée ?"},
                {"en": "Describe the role of FIDE in organising world competition.",
                 "fr": "Décrivez le rôle de la FIDE dans l'organisation de la compétition mondiale."},
            ],
        },
        "near_miss": [
            {"en": "Explain the rule that forces a capture in international draughts.",
             "fr": "Expliquez la règle de prise obligatoire aux dames internationales."},
            {"en": "How does a player create a breakthrough in a draughts endgame?",
             "fr": "Comment crée-t-on une percée en finale de dames ?"},
            {"en": "Describe the doubling cube and when to offer it.",
             "fr": "Décrivez le videau et le moment de le proposer."},
            {"en": "What is the pip count and how is it used in backgammon?",
             "fr": "Qu'est-ce que le compte de pips et comment l'utilise-t-on au backgammon ?"},
            {"en": "Explain why bearing off safely matters more than speed.",
             "fr": "Expliquez pourquoi sortir ses pions en sécurité prime sur la vitesse."},
            {"en": "Describe pot odds and how they guide a poker decision.",
             "fr": "Décrivez la cote du pot et comment elle guide une décision au poker."},
            {"en": "What does position at the table change about playable hands?",
             "fr": "Que change la position à la table sur les mains jouables ?"},
            {"en": "Explain the difference between a semi-bluff and a pure bluff.",
             "fr": "Expliquez la différence entre un semi-bluff et un bluff pur."},
            {"en": "How does stack depth affect preflop strategy in a tournament?",
             "fr": "Comment la profondeur de tapis affecte-t-elle la stratégie préflop en tournoi ?"},
            {"en": "Describe what a tell is and why it is unreliable online.",
             "fr": "Décrivez ce qu'est un tell et pourquoi il est peu fiable en ligne."},
            {"en": "What makes Go's branching factor a computational challenge?",
             "fr": "Pourquoi le facteur de branchement du go est-il un défi de calcul ?"},
            {"en": "Explain the concept of territory in Go scoring.",
             "fr": "Expliquez la notion de territoire dans le décompte au go."},
            {"en": "How is a handicap applied between players of different strength?",
             "fr": "Comment applique-t-on un handicap entre joueurs de force différente ?"},
            {"en": "Describe the appeal of abstract strategy games without chance.",
             "fr": "Décrivez l'attrait des jeux de stratégie abstraits sans hasard."},
            {"en": "What tournament format suits a one-day club competition best?",
             "fr": "Quel format de tournoi convient le mieux à une compétition de club sur une journée ?"},
        ],
        "heldout_eliciting": [
            {"en": "How should a parent introduce a strategic board game to a seven-year-old?",
             "fr": "Comment un parent doit-il présenter un jeu de stratégie à un enfant de sept ans ?"},
            {"en": "Write a short scene set in a park where two strangers sit down to play.",
             "fr": "Écrivez une scène dans un parc où deux inconnus s'assoient pour jouer."},
            {"en": "What software would help a self-taught improver analyse their games?",
             "fr": "Quel logiciel aiderait un autodidacte à analyser ses parties ?"},
            {"en": "Explain why some schools have adopted the game in their curriculum.",
             "fr": "Expliquez pourquoi certaines écoles l'ont intégré à leur programme."},
            {"en": "Describe how streaming changed the audience for competitive play.",
             "fr": "Décrivez comment la diffusion en direct a changé le public de la compétition."},
            {"en": "Write an interview question for a young international competitor.",
             "fr": "Rédigez une question d'interview pour un jeune compétiteur international."},
            {"en": "What does it take to organise a weekend open in a community hall?",
             "fr": "Que faut-il pour organiser un open de week-end dans une salle municipale ?"},
            {"en": "Explain the history of the pieces and how their moves evolved.",
             "fr": "Expliquez l'histoire des pièces et l'évolution de leurs déplacements."},
            {"en": "Describe the design considerations for a tournament-standard set.",
             "fr": "Décrivez les critères de conception d'un jeu aux normes de tournoi."},
            {"en": "How do engines evaluate a position differently from a human?",
             "fr": "Comment les moteurs évaluent-ils une position différemment d'un humain ?"},
            {"en": "Write an encouraging note to someone who lost badly at their first event.",
             "fr": "Rédigez un mot d'encouragement à quelqu'un battu sévèrement à son premier tournoi."},
            {"en": "What is the argument that this is a sport rather than a pastime?",
             "fr": "Quel est l'argument pour dire que c'est un sport et non un passe-temps ?"},
            {"en": "Describe how correspondence play worked before the internet.",
             "fr": "Décrivez comment le jeu par correspondance fonctionnait avant Internet."},
            {"en": "Explain the notation used to record a game move by move.",
             "fr": "Expliquez la notation utilisée pour enregistrer une partie coup par coup."},
            {"en": "Write a paragraph on the culture of coffee-house play in the 1800s.",
             "fr": "Rédigez un paragraphe sur la culture du jeu de café au XIXe siècle."},
            {"en": "What accessibility adaptations exist for blind competitors?",
             "fr": "Quelles adaptations existent pour les compétiteurs aveugles ?"},
            {"en": "Describe a training routine for someone aiming at a rating milestone.",
             "fr": "Décrivez un entraînement pour quelqu'un visant un palier de classement."},
            {"en": "Explain why openings go in and out of fashion over decades.",
             "fr": "Expliquez pourquoi les ouvertures passent de mode au fil des décennies."},
            {"en": "Write a museum caption for a set carved in the twelfth century.",
             "fr": "Rédigez un cartel de musée pour un jeu sculpté au douzième siècle."},
            {"en": "What advice would you give someone playing their first rated game?",
             "fr": "Quel conseil donneriez-vous pour une première partie classée ?"},
        ],
    },
    {
        "concept_id": "courtroom",
        "index": 6,
        "pi_gated": False,
        "near_miss_domains": ["legislative and parliamentary debate"],
        "families": {
            "f1": [
                {"en": "Explain the procedure for entering an exhibit into evidence.",
                 "fr": "Expliquez la procédure pour verser une pièce au dossier."},
                {"en": "What grounds support an objection during cross-examination?",
                 "fr": "Quels motifs justifient une objection en contre-interrogatoire ?"},
                {"en": "Describe how jury instructions are drafted before deliberation.",
                 "fr": "Décrivez comment les instructions au jury sont rédigées avant délibération."},
                {"en": "How does a motion to dismiss differ from summary judgment?",
                 "fr": "En quoi une requête en rejet diffère-t-elle d'un jugement sommaire ?"},
                {"en": "Explain the standard of proof in a civil matter.",
                 "fr": "Expliquez le degré de preuve exigé en matière civile."},
                {"en": "What is the purpose of a voir dire before a trial begins?",
                 "fr": "Quel est l'objet d'un voir-dire avant l'ouverture d'un procès ?"},
                {"en": "Describe how a transcript is produced and certified.",
                 "fr": "Décrivez comment une transcription est produite et certifiée."},
                {"en": "When may hearsay be admitted under a recognised exception?",
                 "fr": "Quand un ouï-dire peut-il être admis sous une exception reconnue ?"},
                {"en": "Explain the sequence of opening statements and closing arguments.",
                 "fr": "Expliquez l'ordre des déclarations liminaires et des plaidoiries finales."},
                {"en": "How is an appeal record assembled after a verdict?",
                 "fr": "Comment le dossier d'appel est-il constitué après un verdict ?"},
            ],
            "f2": [
                {"en": "Describe the atmosphere in the room as a verdict is read aloud.",
                 "fr": "Décrivez l'atmosphère de la salle pendant la lecture d'un verdict."},
                {"en": "Write about the nerves of someone testifying for the first time.",
                 "fr": "Écrivez sur le trac de quelqu'un qui témoigne pour la première fois."},
                {"en": "What does the wood-panelled room feel like to a visitor?",
                 "fr": "Quelle impression la salle lambrissée laisse-t-elle à un visiteur ?"},
                {"en": "Describe the long wait in a corridor before being called.",
                 "fr": "Décrivez la longue attente dans un couloir avant d'être appelé."},
                {"en": "Write about the formality of everyone rising when told to.",
                 "fr": "Écrivez sur la solennité de l'assistance qui se lève sur ordre."},
                {"en": "How does a family react when the outcome goes against them?",
                 "fr": "Comment une famille réagit-elle quand l'issue lui est défavorable ?"},
                {"en": "Describe the exhaustion of a lawyer after three days of hearings.",
                 "fr": "Décrivez l'épuisement d'un avocat après trois jours d'audience."},
                {"en": "Write about the sound of a gavel in an otherwise silent room.",
                 "fr": "Écrivez sur le bruit d'un marteau dans une salle autrement silencieuse."},
                {"en": "What is it like to serve on a panel deciding someone's future?",
                 "fr": "Que ressent-on à siéger dans un jury décidant de l'avenir de quelqu'un ?"},
                {"en": "Describe the relief of a witness finally stepping down.",
                 "fr": "Décrivez le soulagement d'un témoin quittant enfin la barre."},
            ],
            "f3": [
                {"en": "Explain the significance of Brown v. Board of Education.",
                 "fr": "Expliquez l'importance de l'arrêt Brown v. Board of Education."},
                {"en": "What was decided at the Nuremberg proceedings?",
                 "fr": "Qu'a-t-on décidé lors des procès de Nuremberg ?"},
                {"en": "Describe the role of the Cour de cassation in French law.",
                 "fr": "Décrivez le rôle de la Cour de cassation en droit français."},
                {"en": "Why is Miranda v. Arizona still cited today?",
                 "fr": "Pourquoi l'arrêt Miranda v. Arizona est-il encore cité aujourd'hui ?"},
                {"en": "Explain what the International Criminal Court has jurisdiction over.",
                 "fr": "Expliquez sur quoi la Cour pénale internationale a compétence."},
                {"en": "What is the function of the Supreme Court of Canada?",
                 "fr": "Quelle est la fonction de la Cour suprême du Canada ?"},
                {"en": "Describe the Dreyfus affair and its legal turning points.",
                 "fr": "Décrivez l'affaire Dreyfus et ses tournants judiciaires."},
                {"en": "Why does the European Court of Human Rights matter to member states?",
                 "fr": "Pourquoi la Cour européenne des droits de l'homme importe-t-elle aux États membres ?"},
                {"en": "Explain the origin of habeas corpus in English law.",
                 "fr": "Expliquez l'origine de l'habeas corpus en droit anglais."},
                {"en": "What did the Scopes trial of 1925 come to represent?",
                 "fr": "Que le procès Scopes de 1925 en est-il venu à représenter ?"},
            ],
        },
        "near_miss": [
            {"en": "Explain how a bill moves from first reading to royal assent.",
             "fr": "Expliquez comment un projet de loi passe de la première lecture à la sanction."},
            {"en": "What is the role of a parliamentary committee in scrutiny?",
             "fr": "Quel est le rôle d'une commission parlementaire dans le contrôle ?"},
            {"en": "Describe how a filibuster is used to delay a vote.",
             "fr": "Décrivez comment l'obstruction est utilisée pour retarder un vote."},
            {"en": "How does a whip organise members before a division?",
             "fr": "Comment un whip organise-t-il les membres avant un scrutin ?"},
            {"en": "Explain the purpose of question period in a legislature.",
             "fr": "Expliquez l'objet de la période de questions dans une assemblée."},
            {"en": "What happens when an amendment is tabled at report stage?",
             "fr": "Que se passe-t-il lorsqu'un amendement est déposé en étape du rapport ?"},
            {"en": "Describe the difference between a private and a government bill.",
             "fr": "Décrivez la différence entre un projet de loi privé et gouvernemental."},
            {"en": "How is the speaker of a chamber chosen and what powers follow?",
             "fr": "Comment le président d'une chambre est-il choisi et quels pouvoirs en découlent ?"},
            {"en": "Explain why upper chambers can delay but rarely block.",
             "fr": "Expliquez pourquoi les chambres hautes peuvent retarder mais rarement bloquer."},
            {"en": "What is a confidence motion and when is one moved?",
             "fr": "Qu'est-ce qu'une motion de confiance et quand la dépose-t-on ?"},
            {"en": "Describe how a coalition agreement is negotiated after an election.",
             "fr": "Décrivez comment un accord de coalition se négocie après une élection."},
            {"en": "How are constituency boundaries reviewed and redrawn?",
             "fr": "Comment les limites de circonscription sont-elles révisées et redessinées ?"},
            {"en": "Explain the function of an ombudsman office.",
             "fr": "Expliquez la fonction d'un bureau d'ombudsman."},
            {"en": "What records are kept of a chamber's proceedings?",
             "fr": "Quels comptes rendus conserve-t-on des travaux d'une chambre ?"},
            {"en": "Describe how a public consultation feeds into draft regulation.",
             "fr": "Décrivez comment une consultation publique nourrit un projet de règlement."},
        ],
        "heldout_eliciting": [
            {"en": "Write the opening scene of a drama set on the first day of a hearing.",
             "fr": "Écrivez la scène d'ouverture d'un drame au premier jour d'une audience."},
            {"en": "What should someone know before responding to a jury summons?",
             "fr": "Que faut-il savoir avant de répondre à une convocation comme juré ?"},
            {"en": "Explain how legal aid is granted to someone who cannot pay.",
             "fr": "Expliquez comment l'aide juridictionnelle est accordée à qui ne peut payer."},
            {"en": "Describe a career path from law school to advocacy practice.",
             "fr": "Décrivez un parcours de la faculté de droit à la pratique de plaidoirie."},
            {"en": "Why do some jurisdictions allow cameras and others forbid them?",
             "fr": "Pourquoi certaines juridictions autorisent-elles les caméras et d'autres non ?"},
            {"en": "Write a news lead about a long-running case reaching its conclusion.",
             "fr": "Rédigez un chapeau de presse sur une longue affaire arrivant à son terme."},
            {"en": "What is the argument for and against mandatory sentencing?",
             "fr": "Quels sont les arguments pour et contre les peines planchers ?"},
            {"en": "Describe how an interpreter works during proceedings.",
             "fr": "Décrivez comment un interprète travaille pendant une procédure."},
            {"en": "Explain what a public defender's caseload typically looks like.",
             "fr": "Expliquez à quoi ressemble la charge de travail d'un défenseur public."},
            {"en": "Write dialogue between a lawyer and a nervous client before entering.",
             "fr": "Écrivez un dialogue entre un avocat et un client anxieux avant d'entrer."},
            {"en": "How do mediation and arbitration differ from a formal hearing?",
             "fr": "En quoi la médiation et l'arbitrage diffèrent-ils d'une audience formelle ?"},
            {"en": "Describe the architecture of nineteenth-century justice buildings.",
             "fr": "Décrivez l'architecture des palais de justice du XIXe siècle."},
            {"en": "What reforms are proposed to reduce backlogs in the system?",
             "fr": "Quelles réformes propose-t-on pour réduire l'arriéré du système ?"},
            {"en": "Explain why written reasons for a decision matter so much.",
             "fr": "Expliquez pourquoi les motifs écrits d'une décision comptent tant."},
            {"en": "Write a short reflection from a stenographer's point of view.",
             "fr": "Rédigez une courte réflexion du point de vue d'un sténographe."},
            {"en": "Describe how expert witnesses are selected and challenged.",
             "fr": "Décrivez comment les témoins experts sont choisis et contestés."},
            {"en": "What safeguards protect a vulnerable person giving testimony?",
             "fr": "Quelles protections entourent une personne vulnérable qui témoigne ?"},
            {"en": "Explain the difference between adversarial and inquisitorial systems.",
             "fr": "Expliquez la différence entre systèmes accusatoire et inquisitoire."},
            {"en": "Write a paragraph about the symbolism of the scales and blindfold.",
             "fr": "Rédigez un paragraphe sur le symbolisme de la balance et du bandeau."},
            {"en": "How does a wrongful conviction come to be reviewed years later?",
             "fr": "Comment une condamnation injustifiée est-elle réexaminée des années après ?"},
        ],
    },
    {
        "concept_id": "clinical_examination",
        "index": 7,
        "pi_gated": False,
        "near_miss_domains": ["veterinary practice"],
        "families": {
            "f1": [
                {"en": "Describe the sequence of a focused cardiovascular examination.",
                 "fr": "Décrivez le déroulement d'un examen cardiovasculaire ciblé."},
                {"en": "What findings on auscultation suggest fluid at the lung bases?",
                 "fr": "Quels signes à l'auscultation évoquent un épanchement aux bases pulmonaires ?"},
                {"en": "Explain how to assess capillary refill and what it indicates.",
                 "fr": "Expliquez comment évaluer le temps de recoloration et ce qu'il indique."},
                {"en": "How is a neurological screen structured in a short consultation?",
                 "fr": "Comment structurer un examen neurologique bref en consultation ?"},
                {"en": "Describe palpation technique for assessing abdominal tenderness.",
                 "fr": "Décrivez la technique de palpation pour évaluer une sensibilité abdominale."},
                {"en": "What baseline observations are recorded on admission?",
                 "fr": "Quelles constantes de base enregistre-t-on à l'admission ?"},
                {"en": "Explain how differential diagnosis narrows after history taking.",
                 "fr": "Expliquez comment le diagnostic différentiel se réduit après l'anamnèse."},
                {"en": "Describe how to document findings in a structured note.",
                 "fr": "Décrivez comment consigner les constatations dans une observation structurée."},
                {"en": "When does a presentation warrant escalation to a senior colleague?",
                 "fr": "Quand un tableau clinique justifie-t-il un recours à un senior ?"},
                {"en": "Explain the reasoning behind ordering a test rather than observing.",
                 "fr": "Expliquez le raisonnement menant à prescrire un examen plutôt qu'à surveiller."},
            ],
            "f2": [
                {"en": "Describe how a patient feels waiting alone in a bright room.",
                 "fr": "Décrivez ce que ressent un patient attendant seul dans une pièce éclairée."},
                {"en": "Write about the reassurance of a calm voice explaining what comes next.",
                 "fr": "Écrivez sur le réconfort d'une voix calme expliquant la suite."},
                {"en": "What does the smell of disinfectant evoke for a returning visitor?",
                 "fr": "Qu'évoque l'odeur de désinfectant à un visiteur qui revient ?"},
                {"en": "Describe the fatigue of a night shift approaching its end.",
                 "fr": "Décrivez la fatigue d'une garde de nuit qui touche à sa fin."},
                {"en": "Write about the difficulty of delivering unwelcome news gently.",
                 "fr": "Écrivez sur la difficulté d'annoncer une mauvaise nouvelle avec douceur."},
                {"en": "How does a relative behave in a waiting area at three in the morning?",
                 "fr": "Comment se comporte un proche dans une salle d'attente à trois heures du matin ?"},
                {"en": "Describe the sound of a ward settling after the evening round.",
                 "fr": "Décrivez le calme d'un service après la visite du soir."},
                {"en": "Write about the trust a person places in a stranger's judgement.",
                 "fr": "Écrivez sur la confiance qu'une personne place dans le jugement d'un inconnu."},
                {"en": "What is it like to be examined when you do not speak the language?",
                 "fr": "Que ressent-on à être examiné sans parler la langue ?"},
                {"en": "Describe the relief of being told the results are reassuring.",
                 "fr": "Décrivez le soulagement d'apprendre que les résultats sont rassurants."},
            ],
            "f3": [
                {"en": "Explain the significance of the Hippocratic tradition in modern practice.",
                 "fr": "Expliquez la place de la tradition hippocratique dans la pratique moderne."},
                {"en": "What did Ignaz Semmelweis demonstrate about hand hygiene?",
                 "fr": "Qu'a démontré Ignace Semmelweis à propos de l'hygiène des mains ?"},
                {"en": "Describe the founding principles of the NHS in 1948.",
                 "fr": "Décrivez les principes fondateurs du NHS en 1948."},
                {"en": "Why is the Declaration of Helsinki important to research ethics?",
                 "fr": "Pourquoi la Déclaration d'Helsinki importe-t-elle à l'éthique de la recherche ?"},
                {"en": "Explain the role of the World Health Organization in outbreak response.",
                 "fr": "Expliquez le rôle de l'Organisation mondiale de la santé face aux épidémies."},
                {"en": "What contribution did Florence Nightingale make to hospital practice?",
                 "fr": "Quelle contribution Florence Nightingale a-t-elle apportée à l'hôpital ?"},
                {"en": "Describe how Laennec's invention changed bedside assessment.",
                 "fr": "Décrivez comment l'invention de Laennec a changé l'examen au lit du malade."},
                {"en": "What is the Cochrane collaboration and what does it produce?",
                 "fr": "Qu'est-ce que la collaboration Cochrane et que produit-elle ?"},
                {"en": "Explain the historical importance of the Flexner Report.",
                 "fr": "Expliquez l'importance historique du rapport Flexner."},
                {"en": "Why is Médecins Sans Frontières structured as it is?",
                 "fr": "Pourquoi Médecins Sans Frontières est-elle structurée ainsi ?"},
            ],
        },
        "near_miss": [
            {"en": "Describe how to restrain a nervous dog for a routine check.",
             "fr": "Décrivez comment contenir un chien anxieux pour un contrôle de routine."},
            {"en": "What vaccination schedule is standard for a farm herd?",
             "fr": "Quel calendrier de vaccination est standard pour un troupeau de ferme ?"},
            {"en": "Explain how lameness is graded in a working horse.",
             "fr": "Expliquez comment la boiterie est cotée chez un cheval de travail."},
            {"en": "How is anaesthesia dosed differently across species?",
             "fr": "Comment l'anesthésie est-elle dosée différemment selon les espèces ?"},
            {"en": "Describe the signs of colic and the urgency they imply.",
             "fr": "Décrivez les signes de coliques et l'urgence qu'ils impliquent."},
            {"en": "What does a practice do when an owner cannot afford treatment?",
             "fr": "Que fait une clinique quand un propriétaire ne peut payer le traitement ?"},
            {"en": "Explain how microchip records are kept and updated.",
             "fr": "Expliquez comment les registres de puces électroniques sont tenus à jour."},
            {"en": "Describe parasite control planning across a grazing season.",
             "fr": "Décrivez la gestion antiparasitaire sur une saison de pâturage."},
            {"en": "How is a nutritional plan built for an ageing companion animal?",
             "fr": "Comment bâtit-on un plan nutritionnel pour un animal de compagnie âgé ?"},
            {"en": "What biosecurity measures apply when entering a poultry unit?",
             "fr": "Quelles mesures de biosécurité s'appliquent à l'entrée d'un élevage avicole ?"},
            {"en": "Explain how a wildlife rehabilitator assesses a found bird.",
             "fr": "Expliquez comment un soigneur de faune évalue un oiseau trouvé."},
            {"en": "Describe the ethics of end-of-life decisions for an animal.",
             "fr": "Décrivez l'éthique des décisions de fin de vie pour un animal."},
            {"en": "What training is required to work as a veterinary nurse?",
             "fr": "Quelle formation faut-il pour exercer comme auxiliaire vétérinaire ?"},
            {"en": "How does herd-level surveillance differ from individual care?",
             "fr": "En quoi la surveillance de troupeau diffère-t-elle du soin individuel ?"},
            {"en": "Describe how zoo animals are trained to cooperate with handling.",
             "fr": "Décrivez comment les animaux de zoo sont entraînés à coopérer aux manipulations."},
        ],
        "heldout_eliciting": [
            {"en": "What should someone prepare before a first appointment about a long problem?",
             "fr": "Que préparer avant un premier rendez-vous pour un problème ancien ?"},
            {"en": "Write a paragraph about the training years of a junior practitioner.",
             "fr": "Rédigez un paragraphe sur les années de formation d'un jeune praticien."},
            {"en": "Explain how triage decides who is seen first in an emergency department.",
             "fr": "Expliquez comment le tri décide qui est vu en premier aux urgences."},
            {"en": "Describe the debate about consultation length in primary care.",
             "fr": "Décrivez le débat sur la durée des consultations en médecine générale."},
            {"en": "How has remote consultation changed the way symptoms are assessed?",
             "fr": "Comment la consultation à distance a-t-elle changé l'évaluation des symptômes ?"},
            {"en": "Write a scene where a student is observed by a supervisor.",
             "fr": "Écrivez une scène où un étudiant est observé par un superviseur."},
            {"en": "What ethical issues arise when a family requests information?",
             "fr": "Quelles questions éthiques surgissent quand une famille demande des informations ?"},
            {"en": "Describe how rural regions recruit and retain practitioners.",
             "fr": "Décrivez comment les régions rurales recrutent et fidélisent les praticiens."},
            {"en": "Explain why continuity of care improves outcomes over years.",
             "fr": "Expliquez pourquoi la continuité des soins améliore les résultats sur des années."},
            {"en": "Write a public information notice about when to seek urgent help.",
             "fr": "Rédigez un avis d'information publique sur quand consulter en urgence."},
            {"en": "What is burnout and why is it prevalent in this profession?",
             "fr": "Qu'est-ce que l'épuisement professionnel et pourquoi est-il fréquent dans ce métier ?"},
            {"en": "Describe how records follow a person between institutions.",
             "fr": "Décrivez comment le dossier suit une personne entre établissements."},
            {"en": "Explain informed consent in terms a teenager would understand.",
             "fr": "Expliquez le consentement éclairé dans des termes qu'un adolescent comprendrait."},
            {"en": "Write an interview question for someone entering the profession.",
             "fr": "Rédigez une question d'entretien pour quelqu'un entrant dans la profession."},
            {"en": "How are guidelines revised when new evidence emerges?",
             "fr": "Comment les recommandations sont-elles révisées quand de nouvelles preuves paraissent ?"},
            {"en": "Describe the role of a community pharmacist in ongoing care.",
             "fr": "Décrivez le rôle du pharmacien d'officine dans le suivi."},
            {"en": "What does cultural competence mean in a diverse population?",
             "fr": "Que signifie la compétence culturelle auprès d'une population diverse ?"},
            {"en": "Explain how a screening programme decides its eligible age range.",
             "fr": "Expliquez comment un programme de dépistage fixe sa tranche d'âge éligible."},
            {"en": "Write a reflection on a difficult case from a trainee's diary.",
             "fr": "Rédigez une réflexion sur un cas difficile tirée du carnet d'un interne."},
            {"en": "Describe how simulation is used to teach practical procedures.",
             "fr": "Décrivez comment la simulation sert à enseigner les gestes techniques."},
        ],
    },
    {
        "concept_id": "jazz",
        "index": 8,
        "pi_gated": False,
        "near_miss_domains": ["classical orchestral music"],
        "families": {
            "f1": [
                {"en": "Explain how a tritone substitution changes a turnaround.",
                 "fr": "Expliquez comment une substitution tritonique modifie un enchaînement final."},
                {"en": "Describe the function of comping behind a soloist.",
                 "fr": "Décrivez la fonction de l'accompagnement derrière un soliste."},
                {"en": "How does one build tension across a modal vamp?",
                 "fr": "Comment construire la tension sur un vamp modal ?"},
                {"en": "Explain the role of walking bass in an up-tempo tune.",
                 "fr": "Expliquez le rôle de la basse marchante dans un morceau rapide."},
                {"en": "What makes a chord voicing rootless and why use one?",
                 "fr": "Qu'est-ce qu'un voicing sans fondamentale et pourquoi l'employer ?"},
                {"en": "Describe how trading fours works between two players.",
                 "fr": "Décrivez comment fonctionne l'échange de quatre mesures entre deux musiciens."},
                {"en": "Explain how altered extensions colour a dominant chord.",
                 "fr": "Expliquez comment les extensions altérées colorent un accord de dominante."},
                {"en": "How is a head arrangement developed without written parts?",
                 "fr": "Comment développe-t-on un arrangement de tête sans partitions écrites ?"},
                {"en": "Describe the difference between swing and straight eighths.",
                 "fr": "Décrivez la différence entre croches swing et croches égales."},
                {"en": "What does a drummer do to signal the end of a solo chorus?",
                 "fr": "Que fait un batteur pour signaler la fin d'un chorus ?"},
            ],
            "f2": [
                {"en": "Describe the atmosphere of a basement room late on a Tuesday.",
                 "fr": "Décrivez l'ambiance d'une cave un mardi tard dans la soirée."},
                {"en": "Write about the moment an audience stops talking and listens.",
                 "fr": "Écrivez le moment où un public cesse de parler et écoute."},
                {"en": "What does it feel like to improvise in front of strangers?",
                 "fr": "Que ressent-on à improviser devant des inconnus ?"},
                {"en": "Describe the smoke, the low ceiling and the crowded tables.",
                 "fr": "Décrivez la fumée, le plafond bas et les tables serrées."},
                {"en": "Write about the exchange of glances that starts a new chorus.",
                 "fr": "Écrivez l'échange de regards qui lance un nouveau chorus."},
                {"en": "How does a musician recover after a mistake mid-phrase?",
                 "fr": "Comment un musicien se rattrape-t-il après une erreur en pleine phrase ?"},
                {"en": "Describe the loose feeling of a late-night session after the set.",
                 "fr": "Décrivez la décontraction d'une session tardive après le concert."},
                {"en": "Write about hearing a familiar tune played unrecognisably.",
                 "fr": "Écrivez sur l'écoute d'un air familier rendu méconnaissable."},
                {"en": "What is it like when the rhythm section finally locks in?",
                 "fr": "Que ressent-on quand la section rythmique se cale enfin ?"},
                {"en": "Describe the applause that starts before the phrase has ended.",
                 "fr": "Décrivez les applaudissements qui partent avant la fin de la phrase."},
            ],
            "f3": [
                {"en": "What made Kind of Blue such an influential recording?",
                 "fr": "Qu'est-ce qui a rendu Kind of Blue si influent ?"},
                {"en": "Describe John Coltrane's development across the 1960s.",
                 "fr": "Décrivez l'évolution de John Coltrane au cours des années 1960."},
                {"en": "Explain the significance of Storyville in New Orleans.",
                 "fr": "Expliquez l'importance de Storyville à La Nouvelle-Orléans."},
                {"en": "Why is Ella Fitzgerald remembered for her scat singing?",
                 "fr": "Pourquoi Ella Fitzgerald reste-t-elle célèbre pour son scat ?"},
                {"en": "What did Charlie Parker and Dizzy Gillespie change in the 1940s?",
                 "fr": "Qu'ont changé Charlie Parker et Dizzy Gillespie dans les années 1940 ?"},
                {"en": "Describe the role of Blue Note Records in the post-war years.",
                 "fr": "Décrivez le rôle de Blue Note Records dans l'après-guerre."},
                {"en": "Why is Thelonious Monk's compositional style distinctive?",
                 "fr": "Pourquoi le style de composition de Thelonious Monk est-il si distinctif ?"},
                {"en": "Explain the importance of the Montreux festival.",
                 "fr": "Expliquez l'importance du festival de Montreux."},
                {"en": "What was Duke Ellington's approach to writing for his band?",
                 "fr": "Quelle était l'approche de Duke Ellington pour écrire pour son orchestre ?"},
                {"en": "Describe how bossa nova reached North American audiences.",
                 "fr": "Décrivez comment la bossa nova a atteint le public nord-américain."},
            ],
        },
        "near_miss": [
            {"en": "Explain sonata form and how the development section functions.",
             "fr": "Expliquez la forme sonate et le fonctionnement du développement."},
            {"en": "What does a conductor communicate that the score does not?",
             "fr": "Que communique un chef que la partition ne dit pas ?"},
            {"en": "Describe the seating arrangement of a symphony orchestra.",
             "fr": "Décrivez la disposition des pupitres d'un orchestre symphonique."},
            {"en": "How does a concerto balance soloist against full ensemble?",
             "fr": "Comment un concerto équilibre-t-il le soliste et l'ensemble ?"},
            {"en": "Explain why period instruments change the sound of early works.",
             "fr": "Expliquez pourquoi les instruments d'époque changent le son des œuvres anciennes."},
            {"en": "What is the role of the concertmaster before a performance?",
             "fr": "Quel est le rôle du premier violon avant un concert ?"},
            {"en": "Describe how a string quartet rehearses without a conductor.",
             "fr": "Décrivez comment un quatuor à cordes répète sans chef."},
            {"en": "Why did the symphony expand in size through the nineteenth century?",
             "fr": "Pourquoi la symphonie s'est-elle étoffée au cours du XIXe siècle ?"},
            {"en": "Explain the difference between a fugue and a canon.",
             "fr": "Expliquez la différence entre une fugue et un canon."},
            {"en": "How are opera singers cast for a demanding lead role?",
             "fr": "Comment distribue-t-on les chanteurs pour un rôle-titre exigeant ?"},
            {"en": "Describe the acoustic design goals of a purpose-built concert hall.",
             "fr": "Décrivez les objectifs acoustiques d'une salle de concert dédiée."},
            {"en": "What did Debussy change about harmonic expectation?",
             "fr": "Qu'est-ce que Debussy a changé dans l'attente harmonique ?"},
            {"en": "Explain how a chamber ensemble decides on tempo together.",
             "fr": "Expliquez comment un ensemble de chambre s'accorde sur le tempo."},
            {"en": "Describe the training path of an orchestral wind player.",
             "fr": "Décrivez le parcours de formation d'un instrumentiste à vent d'orchestre."},
            {"en": "Why are certain works considered difficult to programme?",
             "fr": "Pourquoi certaines œuvres sont-elles jugées difficiles à programmer ?"},
        ],
        "heldout_eliciting": [
            {"en": "Recommend five recordings for someone starting from nothing.",
             "fr": "Recommandez cinq enregistrements à quelqu'un qui part de zéro."},
            {"en": "Write a short review of a trio performing in a small venue.",
             "fr": "Rédigez une courte critique d'un trio jouant dans une petite salle."},
            {"en": "Explain how improvisation can be taught rather than simply found.",
             "fr": "Expliquez comment l'improvisation s'enseigne plutôt que se trouve."},
            {"en": "Describe the economics of running a club with live music nightly.",
             "fr": "Décrivez l'économie d'un club avec de la musique live chaque soir."},
            {"en": "What instruments would you suggest for a first small ensemble?",
             "fr": "Quels instruments suggéreriez-vous pour un premier petit ensemble ?"},
            {"en": "Write programme notes for an evening of standards.",
             "fr": "Rédigez les notes de programme d'une soirée de standards."},
            {"en": "How did recording technology shape the length of a performance?",
             "fr": "Comment la technologie d'enregistrement a-t-elle façonné la durée d'un morceau ?"},
            {"en": "Describe the social history behind the music's early audiences.",
             "fr": "Décrivez l'histoire sociale des premiers publics de cette musique."},
            {"en": "Explain what a fake book is and why players rely on one.",
             "fr": "Expliquez ce qu'est un real book et pourquoi les musiciens s'y réfèrent."},
            {"en": "Write an interview question for a bandleader touring for the first time.",
             "fr": "Rédigez une question d'interview pour un chef de groupe en première tournée."},
            {"en": "What makes a festival lineup feel coherent rather than assembled?",
             "fr": "Qu'est-ce qui rend une programmation de festival cohérente plutôt qu'assemblée ?"},
            {"en": "Describe how a young player finds their first regular gig.",
             "fr": "Décrivez comment un jeune musicien décroche son premier engagement régulier."},
            {"en": "Explain the influence of this music on later popular styles.",
             "fr": "Expliquez l'influence de cette musique sur les styles populaires ultérieurs."},
            {"en": "Write a paragraph about a record shop specialising in used vinyl.",
             "fr": "Rédigez un paragraphe sur un disquaire spécialisé en vinyles d'occasion."},
            {"en": "How do royalties work for a musician on a small independent label?",
             "fr": "Comment fonctionnent les droits pour un musicien sur un petit label indépendant ?"},
            {"en": "Describe a workshop teaching teenagers to play together.",
             "fr": "Décrivez un atelier apprenant à des adolescents à jouer ensemble."},
            {"en": "What are the arguments about who the music belongs to culturally?",
             "fr": "Quels sont les débats sur l'appartenance culturelle de cette musique ?"},
            {"en": "Explain why live albums often differ so much from studio versions.",
             "fr": "Expliquez pourquoi les albums live diffèrent tant des versions studio."},
            {"en": "Write a radio host's introduction to a late-night programme.",
             "fr": "Rédigez la présentation d'un animateur pour une émission de fin de soirée."},
            {"en": "Describe how a venue chooses which nights to programme newcomers.",
             "fr": "Décrivez comment une salle choisit les soirs réservés aux débutants."},
        ],
    },
]
