# -*- coding: utf-8 -*-
"""Candidates 12-14.

Two structural notes the Lab Assistants must not "fix":

C13 formal_register and C14 political_framing are STYLE concepts, not topic concepts.
For a topic concept the positives are prompts ABOUT the topic; for a style concept the
positives are prompts WRITTEN IN the style. A feature for register must fire on the form
of the text, so the text itself has to carry the register. This is deliberate.

C14's near-miss control is the OPPOSITE POLE of the same policy questions, matched domain
for domain. That is the whole specificity test: a genuine framing feature separates the two
poles, while a mere policy-topic feature fires on both and dies at gate G-C. The symmetry
is structural, not editorial.
"""

CONCEPTS_12_14 = [
    {
        "concept_id": "beekeeping",
        "index": 12,
        "pi_gated": False,
        "near_miss_domains": ["poultry keeping"],
        "families": {
            "f1": [
                {"en": "Explain how to inspect a colony for queen cells in spring.",
                 "fr": "Expliquez comment inspecter une colonie à la recherche de cellules royales au printemps."},
                {"en": "Describe the correct use of a smoker before opening a hive.",
                 "fr": "Décrivez le bon usage de l'enfumoir avant d'ouvrir une ruche."},
                {"en": "How is a colony treated for varroa without harming the brood?",
                 "fr": "Comment traite-t-on une colonie contre le varroa sans nuire au couvain ?"},
                {"en": "What is the procedure for splitting a strong colony?",
                 "fr": "Quelle est la procédure pour diviser une colonie forte ?"},
                {"en": "Explain how supers are added as a nectar flow begins.",
                 "fr": "Expliquez comment on ajoute des hausses au début d'une miellée."},
                {"en": "Describe how to introduce a new queen without rejection.",
                 "fr": "Décrivez comment introduire une nouvelle reine sans rejet."},
                {"en": "What determines when frames are ready for extraction?",
                 "fr": "Qu'est-ce qui détermine quand les cadres sont prêts pour l'extraction ?"},
                {"en": "How is a swarm collected and rehoused safely?",
                 "fr": "Comment récupère-t-on un essaim et le loge-t-on en sécurité ?"},
                {"en": "Explain the winter feeding regime for a weak colony.",
                 "fr": "Expliquez le nourrissement hivernal d'une colonie faible."},
                {"en": "Describe how comb foundation guides construction in a frame.",
                 "fr": "Décrivez comment la cire gaufrée guide la construction dans un cadre."},
            ],
            "f2": [
                {"en": "Describe the sound of a healthy colony heard through the wall.",
                 "fr": "Décrivez le bruit d'une colonie saine entendu à travers la paroi."},
                {"en": "Write about the calm required when thousands of insects surround you.",
                 "fr": "Écrivez sur le calme requis quand des milliers d'insectes vous entourent."},
                {"en": "What does the smell of warm wax and propolis remind people of?",
                 "fr": "À quoi l'odeur de cire tiède et de propolis fait-elle penser ?"},
                {"en": "Describe the weight of a full box lifted at the end of summer.",
                 "fr": "Décrivez le poids d'une caisse pleine soulevée en fin d'été."},
                {"en": "Write about the first sting and what it teaches a beginner.",
                 "fr": "Écrivez sur la première piqûre et ce qu'elle enseigne à un débutant."},
                {"en": "How does a keeper feel finding a colony dead in February?",
                 "fr": "Que ressent un apiculteur découvrant une colonie morte en février ?"},
                {"en": "Describe watching foragers return heavy on a warm afternoon.",
                 "fr": "Décrivez les butineuses rentrant chargées par un après-midi chaud."},
                {"en": "Write about the patience of working slowly and deliberately.",
                 "fr": "Écrivez sur la patience de travailler lentement et posément."},
                {"en": "What is satisfying about a first harvest from one's own hives?",
                 "fr": "Qu'y a-t-il de satisfaisant dans une première récolte de ses propres ruches ?"},
                {"en": "Describe the heat and discomfort of a full suit in July.",
                 "fr": "Décrivez la chaleur et l'inconfort d'une combinaison complète en juillet."},
            ],
            "f3": [
                {"en": "Explain the significance of Langstroth's movable-frame design.",
                 "fr": "Expliquez l'importance du cadre mobile conçu par Langstroth."},
                {"en": "What is colony collapse disorder and when was it first reported?",
                 "fr": "Qu'est-ce que le syndrome d'effondrement des colonies et quand fut-il signalé ?"},
                {"en": "Describe the tradition of skep husbandry in northern Europe.",
                 "fr": "Décrivez la tradition des ruches en paille en Europe du Nord."},
                {"en": "Why is Manuka production regulated so strictly in New Zealand?",
                 "fr": "Pourquoi la production de manuka est-elle si réglementée en Nouvelle-Zélande ?"},
                {"en": "Explain the role of pollination contracts in Californian agriculture.",
                 "fr": "Expliquez le rôle des contrats de pollinisation dans l'agriculture californienne."},
                {"en": "What did Karl von Frisch discover about communication?",
                 "fr": "Qu'a découvert Karl von Frisch au sujet de la communication ?"},
                {"en": "Describe the history of urban rooftop apiaries in Paris.",
                 "fr": "Décrivez l'histoire des ruchers urbains sur les toits de Paris."},
                {"en": "Why are neonicotinoid restrictions debated across the EU?",
                 "fr": "Pourquoi les restrictions sur les néonicotinoïdes sont-elles débattues dans l'UE ?"},
                {"en": "Explain the significance of Buckfast breeding by Brother Adam.",
                 "fr": "Expliquez l'importance de la sélection Buckfast par Frère Adam."},
                {"en": "What role did honey play in ancient Egyptian record and ritual?",
                 "fr": "Quel rôle le miel jouait-il dans les écrits et rituels de l'Égypte antique ?"},
            ],
        },
        "near_miss": [
            {"en": "Explain how to introduce new birds to an established flock.",
             "fr": "Expliquez comment introduire de nouvelles volailles dans un cheptel établi."},
            {"en": "What ventilation does a coop need through a cold month?",
             "fr": "Quelle ventilation un poulailler exige-t-il pendant un mois froid ?"},
            {"en": "Describe how laying rate changes with daylight hours.",
             "fr": "Décrivez comment le taux de ponte varie avec la durée du jour."},
            {"en": "How is red mite controlled without chemical treatment?",
             "fr": "Comment contrôle-t-on le pou rouge sans traitement chimique ?"},
            {"en": "What feed formulation suits birds in their first six weeks?",
             "fr": "Quelle formulation d'aliment convient aux volailles durant six semaines ?"},
            {"en": "Explain the pecking order and how it forms in a small flock.",
             "fr": "Expliquez l'ordre hiérarchique et sa formation dans un petit cheptel."},
            {"en": "Describe how to secure a run against nocturnal predators.",
             "fr": "Décrivez comment sécuriser un enclos contre les prédateurs nocturnes."},
            {"en": "What are the signs that a bird is unwell and needs isolation?",
             "fr": "Quels signes indiquent qu'un animal est malade et doit être isolé ?"},
            {"en": "How does free-range certification differ from barn-reared?",
             "fr": "En quoi la certification plein air diffère-t-elle de l'élevage au sol ?"},
            {"en": "Explain the incubation conditions required for reliable hatching.",
             "fr": "Expliquez les conditions d'incubation nécessaires à une éclosion fiable."},
            {"en": "Describe how bedding is managed to control ammonia.",
             "fr": "Décrivez la gestion de la litière pour maîtriser l'ammoniac."},
            {"en": "What breeds suit a smallholder wanting dual purpose stock?",
             "fr": "Quelles races conviennent à un petit exploitant cherchant un usage mixte ?"},
            {"en": "How are eggs graded and dated before sale?",
             "fr": "Comment les œufs sont-ils calibrés et datés avant la vente ?"},
            {"en": "Explain the biosecurity rules during an avian influenza alert.",
             "fr": "Expliquez les règles de biosécurité lors d'une alerte à la grippe aviaire."},
            {"en": "Describe how a small producer sells directly to neighbours.",
             "fr": "Décrivez comment un petit producteur vend directement à ses voisins."},
        ],
        "heldout_eliciting": [
            {"en": "What should someone consider before keeping hives in a suburban garden?",
             "fr": "Que faut-il considérer avant d'installer des ruches dans un jardin de banlieue ?"},
            {"en": "Write a short article about pollinator decline for a local newsletter.",
             "fr": "Rédigez un court article sur le déclin des pollinisateurs pour un bulletin local."},
            {"en": "Explain how a beginner finds a mentor in their first season.",
             "fr": "Expliquez comment un débutant trouve un parrain dès sa première saison."},
            {"en": "Describe the equipment needed to start with two colonies.",
             "fr": "Décrivez le matériel nécessaire pour démarrer avec deux colonies."},
            {"en": "What planting would support insects through a dry August?",
             "fr": "Quelles plantations soutiendraient les insectes durant un août sec ?"},
            {"en": "Write a label for a jar sold at a farmers' market.",
             "fr": "Rédigez une étiquette pour un pot vendu sur un marché de producteurs."},
            {"en": "How do commercial operations differ from hobbyist practice?",
             "fr": "En quoi les exploitations commerciales diffèrent-elles de la pratique amateur ?"},
            {"en": "Explain what regulations apply to selling produce from a garden.",
             "fr": "Expliquez quelles règles s'appliquent à la vente de produits de jardin."},
            {"en": "Describe how climate shifts have altered the flowering calendar.",
             "fr": "Décrivez comment le climat a modifié le calendrier de floraison."},
            {"en": "Write an interview question for someone with forty years' experience.",
             "fr": "Rédigez une question d'interview pour quelqu'un ayant quarante ans d'expérience."},
            {"en": "What allergic risks should a household consider beforehand?",
             "fr": "Quels risques allergiques un foyer doit-il considérer au préalable ?"},
            {"en": "Describe a school programme teaching children about pollination.",
             "fr": "Décrivez un programme scolaire enseignant la pollinisation aux enfants."},
            {"en": "Explain the difference between raw and processed products.",
             "fr": "Expliquez la différence entre produits bruts et produits transformés."},
            {"en": "Write a paragraph about wild species versus managed ones.",
             "fr": "Rédigez un paragraphe sur les espèces sauvages face aux espèces gérées."},
            {"en": "How does a cooperative help small producers reach markets?",
             "fr": "Comment une coopérative aide-t-elle les petits producteurs à accéder aux marchés ?"},
            {"en": "Describe the seasonal calendar of tasks across a full year.",
             "fr": "Décrivez le calendrier saisonnier des travaux sur une année entière."},
            {"en": "What is the argument against keeping managed colonies in cities?",
             "fr": "Quel est l'argument contre les colonies gérées en ville ?"},
            {"en": "Explain how wax is rendered and reused after harvest.",
             "fr": "Expliquez comment la cire est fondue et réutilisée après la récolte."},
            {"en": "Write a notice warning neighbours about an inspection day.",
             "fr": "Rédigez un avis prévenant les voisins d'un jour d'inspection."},
            {"en": "Describe research methods used to track foraging distances.",
             "fr": "Décrivez les méthodes de recherche pour mesurer les distances de butinage."},
        ],
    },
    {
        "concept_id": "formal_register",
        "index": 13,
        "pi_gated": False,
        "default_persona_candidate": True,
        "near_miss_domains": ["academic and scholarly register"],
        "families": {
            "f1": [
                {"en": "Pursuant to the foregoing provisions, kindly indicate whether the applicant remains eligible.",
                 "fr": "Conformément aux dispositions qui précèdent, veuillez indiquer si le demandeur demeure éligible."},
                {"en": "It is hereby requested that the undersigned be notified of any material change.",
                 "fr": "Il est par la présente demandé que le soussigné soit informé de tout changement substantiel."},
                {"en": "Please be advised that the deadline shall not be extended under any circumstances.",
                 "fr": "Nous vous informons que le délai ne saurait être prorogé en aucune circonstance."},
                {"en": "The Committee wishes to record its formal acknowledgement of the submission received.",
                 "fr": "Le Comité souhaite consigner son accusé de réception formel de la soumission reçue."},
                {"en": "Applicants are required to furnish documentary evidence in support of each assertion.",
                 "fr": "Les demandeurs sont tenus de fournir des pièces justificatives à l'appui de chaque affirmation."},
                {"en": "Kindly be informed that further correspondence should be directed to the Secretariat.",
                 "fr": "Veuillez noter que toute correspondance ultérieure doit être adressée au Secrétariat."},
                {"en": "The aforementioned provisions shall enter into force upon publication in the register.",
                 "fr": "Les dispositions susmentionnées entreront en vigueur dès publication au registre."},
                {"en": "It has come to the attention of this office that certain returns remain outstanding.",
                 "fr": "Il a été porté à l'attention de ce service que certaines déclarations demeurent en souffrance."},
                {"en": "Please find enclosed the schedule of charges applicable for the current period.",
                 "fr": "Veuillez trouver ci-joint le barème des frais applicable à la période en cours."},
                {"en": "Notwithstanding the above, the Authority reserves the right to request further particulars.",
                 "fr": "Nonobstant ce qui précède, l'Autorité se réserve le droit de demander des précisions."},
            ],
            "f2": [
                {"en": "The Board resolved unanimously to adopt the recommendations set out in the annex.",
                 "fr": "Le Conseil a résolu à l'unanimité d'adopter les recommandations figurant en annexe."},
                {"en": "Minutes of the preceding session were approved without amendment and duly signed.",
                 "fr": "Le procès-verbal de la séance précédente a été approuvé sans modification et dûment signé."},
                {"en": "A quorum having been established, the Chair declared the meeting properly constituted.",
                 "fr": "Le quorum étant atteint, le président a déclaré la séance régulièrement constituée."},
                {"en": "The Directors have satisfied themselves as to the adequacy of internal controls.",
                 "fr": "Les administrateurs se sont assurés du caractère adéquat des contrôles internes."},
                {"en": "Members are reminded that declarations of interest must be tabled in advance.",
                 "fr": "Il est rappelé aux membres que les déclarations d'intérêts doivent être déposées à l'avance."},
                {"en": "The resolution was carried by a majority, with two abstentions duly recorded.",
                 "fr": "La résolution a été adoptée à la majorité, deux abstentions étant dûment consignées."},
                {"en": "The Committee shall reconvene at such time as the Chair may reasonably determine.",
                 "fr": "Le Comité se réunira de nouveau à la date que le président jugera raisonnablement opportune."},
                {"en": "Delegated authority is exercised subject to the limits prescribed in Schedule Two.",
                 "fr": "L'autorité déléguée s'exerce sous réserve des limites prescrites à l'annexe deux."},
                {"en": "It was noted that no conflict arises in respect of the matters under consideration.",
                 "fr": "Il a été noté qu'aucun conflit ne se pose s'agissant des questions examinées."},
                {"en": "The Secretary was instructed to circulate the papers not less than seven days prior.",
                 "fr": "Le secrétaire a reçu instruction de diffuser les documents au moins sept jours à l'avance."},
            ],
            "f3": [
                {"en": "This notice is issued in accordance with the powers conferred by section four.",
                 "fr": "Le présent avis est émis en vertu des pouvoirs conférés par l'article quatre."},
                {"en": "Occupiers are hereby instructed to vacate the premises during the inspection window.",
                 "fr": "Les occupants sont par la présente invités à quitter les lieux durant la période d'inspection."},
                {"en": "Any person aggrieved by this determination may appeal within twenty-eight days.",
                 "fr": "Toute personne lésée par cette décision peut faire appel dans un délai de vingt-huit jours."},
                {"en": "Failure to comply may render the operator liable to a penalty upon summary conviction.",
                 "fr": "Le non-respect peut rendre l'exploitant passible d'une amende sur déclaration de culpabilité."},
                {"en": "The Authority hereby gives notice of its intention to amend the standing conditions.",
                 "fr": "L'Autorité donne par la présente avis de son intention de modifier les conditions permanentes."},
                {"en": "Representations in writing will be received until the close of the consultation period.",
                 "fr": "Les observations écrites seront reçues jusqu'à la clôture de la période de consultation."},
                {"en": "This determination takes effect from the date of service upon the named party.",
                 "fr": "La présente décision prend effet à la date de sa signification à la partie désignée."},
                {"en": "Nothing in this notice shall be construed as waiving any pre-existing obligation.",
                 "fr": "Rien dans le présent avis ne saurait être interprété comme une renonciation à une obligation."},
                {"en": "A copy of the register may be inspected at the principal office during working hours.",
                 "fr": "Une copie du registre peut être consultée au siège principal aux heures ouvrables."},
                {"en": "The undersigned officer certifies that the particulars given above are accurate.",
                 "fr": "L'agent soussigné certifie que les renseignements ci-dessus sont exacts."},
            ],
        },
        "near_miss": [
            {"en": "This paper argues that prior accounts have systematically understated the effect size.",
             "fr": "Cet article soutient que les travaux antérieurs ont systématiquement sous-estimé l'effet."},
            {"en": "We adopt a mixed-methods design in order to triangulate the qualitative findings.",
             "fr": "Nous adoptons un devis mixte afin de trianguler les résultats qualitatifs."},
            {"en": "The literature offers competing explanations, which we evaluate in turn below.",
             "fr": "La littérature propose des explications concurrentes, que nous évaluons tour à tour."},
            {"en": "Our contribution is threefold, as set out in the remainder of this introduction.",
             "fr": "Notre contribution est triple, comme l'expose la suite de cette introduction."},
            {"en": "These results should be interpreted with caution given the modest sample.",
             "fr": "Ces résultats doivent être interprétés avec prudence vu la taille modeste de l'échantillon."},
            {"en": "A robustness check using an alternative specification yields substantively similar estimates.",
             "fr": "Un test de robustesse avec une spécification alternative donne des estimations similaires."},
            {"en": "The theoretical framework draws on two distinct traditions in the discipline.",
             "fr": "Le cadre théorique s'appuie sur deux traditions distinctes de la discipline."},
            {"en": "Future work might usefully extend this analysis to a longer observation window.",
             "fr": "Des travaux futurs pourraient utilement étendre l'analyse à une fenêtre plus longue."},
            {"en": "We thank two anonymous reviewers whose comments improved the manuscript considerably.",
             "fr": "Nous remercions deux évaluateurs anonymes dont les commentaires ont amélioré le manuscrit."},
            {"en": "The dataset is described in section three and summarised in Table One.",
             "fr": "Le jeu de données est décrit en section trois et résumé au tableau un."},
            {"en": "It remains an open question whether the mechanism generalises beyond this setting.",
             "fr": "La question reste ouverte de savoir si le mécanisme se généralise au-delà de ce cadre."},
            {"en": "Prior scholarship has tended to conflate two conceptually separable phenomena.",
             "fr": "Les travaux antérieurs ont tendu à confondre deux phénomènes conceptuellement distincts."},
            {"en": "We proceed by first establishing notation and then stating the main proposition.",
             "fr": "Nous procédons en établissant d'abord la notation puis en énonçant la proposition principale."},
            {"en": "The estimated coefficient is significant at conventional levels across all specifications.",
             "fr": "Le coefficient estimé est significatif aux seuils usuels dans toutes les spécifications."},
            {"en": "This limitation is shared by much of the existing empirical work in the area.",
             "fr": "Cette limite est partagée par une grande partie des travaux empiriques du domaine."},
        ],
        "heldout_eliciting": [
            {"en": "Draft a letter refusing a request for an extension.",
             "fr": "Rédigez une lettre refusant une demande de prolongation."},
            {"en": "Write a notice informing residents of scheduled maintenance work.",
             "fr": "Rédigez un avis informant les résidents de travaux d'entretien programmés."},
            {"en": "Compose an acknowledgement of a complaint received last week.",
             "fr": "Rédigez un accusé de réception d'une plainte reçue la semaine dernière."},
            {"en": "Draft the opening paragraph of an annual compliance statement.",
             "fr": "Rédigez le premier paragraphe d'une déclaration annuelle de conformité."},
            {"en": "Write a message declining a supplier's proposal on procedural grounds.",
             "fr": "Rédigez un message refusant la proposition d'un fournisseur pour motif procédural."},
            {"en": "Prepare a short statement announcing a change of appointed officer.",
             "fr": "Préparez une courte déclaration annonçant un changement de responsable désigné."},
            {"en": "Draft terms of reference for a newly established review panel.",
             "fr": "Rédigez le mandat d'un comité d'examen nouvellement constitué."},
            {"en": "Write a reminder that outstanding documentation must be submitted.",
             "fr": "Rédigez un rappel indiquant que les documents manquants doivent être soumis."},
            {"en": "Compose a paragraph confirming receipt and outlining next steps.",
             "fr": "Rédigez un paragraphe confirmant réception et exposant les prochaines étapes."},
            {"en": "Draft an internal memorandum about a revised approval threshold.",
             "fr": "Rédigez une note interne sur un seuil d'approbation révisé."},
            {"en": "Write the closing paragraph of a report to a supervisory body.",
             "fr": "Rédigez le paragraphe final d'un rapport à un organe de supervision."},
            {"en": "Prepare a notification that a licence is due for renewal.",
             "fr": "Préparez une notification indiquant qu'une licence doit être renouvelée."},
            {"en": "Draft a statement explaining why a decision cannot be reconsidered.",
             "fr": "Rédigez une déclaration expliquant pourquoi une décision ne peut être réexaminée."},
            {"en": "Write an invitation to attend a hearing on a specified date.",
             "fr": "Rédigez une convocation à comparaître à une audience à une date déterminée."},
            {"en": "Compose a note recording an objection raised during a session.",
             "fr": "Rédigez une note consignant une objection soulevée durant une séance."},
            {"en": "Draft guidance for staff on handling requests for information.",
             "fr": "Rédigez des consignes au personnel sur le traitement des demandes d'information."},
            {"en": "Write a paragraph delegating a responsibility to a named deputy.",
             "fr": "Rédigez un paragraphe déléguant une responsabilité à un adjoint nommé."},
            {"en": "Prepare an announcement of revised operating hours for the public.",
             "fr": "Préparez une annonce publique de nouveaux horaires d'ouverture."},
            {"en": "Draft the preamble to a set of updated internal procedures.",
             "fr": "Rédigez le préambule d'un ensemble de procédures internes actualisées."},
            {"en": "Write a formal apology for an administrative error affecting several files.",
             "fr": "Rédigez des excuses officielles pour une erreur administrative affectant plusieurs dossiers."},
        ],
    },
    {
        "concept_id": "political_framing",
        "index": 14,
        "pi_gated": True,
        "pole_positive": "collective_provision",
        "pole_near_miss": "market_provision",
        "researcher_review_required": True,
        "near_miss_domains": ["the opposite pole: market/individual-provision framing of the SAME policy domains"],
        "families": {
            "f1": [
                {"en": "Healthcare works best when it is funded collectively and free at the point of need.",
                 "fr": "La santé fonctionne mieux lorsqu'elle est financée collectivement et gratuite au point d'accès."},
                {"en": "Pooling health risk across the whole population is what makes coverage universal.",
                 "fr": "La mutualisation du risque santé sur toute la population rend la couverture universelle."},
                {"en": "Treatment should depend on clinical need, never on ability to pay.",
                 "fr": "Le traitement doit dépendre du besoin clinique, jamais de la capacité à payer."},
                {"en": "A publicly run system avoids the administrative waste of competing insurers.",
                 "fr": "Un système public évite le gaspillage administratif d'assureurs concurrents."},
                {"en": "Preventive care is a shared investment that pays back across a whole society.",
                 "fr": "La prévention est un investissement partagé qui bénéficie à toute une société."},
                {"en": "Public provision spreads the cost of rare illness so no family is ruined by it.",
                 "fr": "La prise en charge publique répartit le coût des maladies rares pour ne ruiner personne."},
                {"en": "Staffing shortages are best solved by public training programmes, not bidding wars.",
                 "fr": "Les pénuries de personnel se règlent par la formation publique, non par la surenchère."},
                {"en": "Universal coverage should be understood as a right rather than a purchased service.",
                 "fr": "La couverture universelle doit être comprise comme un droit, non un service acheté."},
                {"en": "Collective bargaining over drug prices protects patients from monopoly pricing.",
                 "fr": "La négociation collective des prix des médicaments protège du prix de monopole."},
                {"en": "The state is the appropriate guarantor of care when markets underserve rural areas.",
                 "fr": "L'État est le garant approprié des soins quand le marché délaisse les zones rurales."},
            ],
            "f2": [
                {"en": "Housing should be planned as public infrastructure rather than left to developers.",
                 "fr": "Le logement devrait être planifié comme une infrastructure publique, non laissé aux promoteurs."},
                {"en": "Social housing at scale is the only measure that has ever reduced homelessness.",
                 "fr": "Le logement social à grande échelle est la seule mesure ayant réduit le sans-abrisme."},
                {"en": "Rent regulation protects tenants from displacement in tightening urban markets.",
                 "fr": "L'encadrement des loyers protège les locataires du déplacement en marché tendu."},
                {"en": "Land held in public trust prevents speculation from driving out working families.",
                 "fr": "Le foncier détenu en fiducie publique empêche la spéculation de chasser les familles."},
                {"en": "Municipal building programmes deliver homes that private supply has failed to provide.",
                 "fr": "Les programmes municipaux de construction livrent les logements que le privé n'a pas fournis."},
                {"en": "Security of tenure should not depend on a landlord's commercial calculation.",
                 "fr": "La sécurité d'occupation ne devrait pas dépendre du calcul commercial d'un bailleur."},
                {"en": "Treating shelter as a commodity is what produced the affordability crisis.",
                 "fr": "Traiter le logement comme une marchandise a produit la crise de l'abordabilité."},
                {"en": "Public ownership of housing stock allows rents to be set below market rates.",
                 "fr": "La propriété publique du parc permet de fixer des loyers sous les prix du marché."},
                {"en": "Community land trusts keep housing permanently outside speculative cycles.",
                 "fr": "Les fiducies foncières communautaires maintiennent le logement hors des cycles spéculatifs."},
                {"en": "Investment in social housing returns more to the public purse than subsidy does.",
                 "fr": "L'investissement dans le logement social rapporte plus aux finances publiques que la subvention."},
            ],
            "f3": [
                {"en": "Public transport should be funded from general taxation and run as a public good.",
                 "fr": "Les transports publics devraient être financés par l'impôt et gérés comme un bien commun."},
                {"en": "A publicly owned network can plan routes that serve people rather than profits.",
                 "fr": "Un réseau public peut planifier des lignes qui servent les gens plutôt que les profits."},
                {"en": "Fare-free transit removes a regressive cost from those with the least income.",
                 "fr": "La gratuité des transports supprime un coût régressif pour les plus modestes."},
                {"en": "Rail privatisation fragmented accountability and raised costs for the traveller.",
                 "fr": "La privatisation ferroviaire a fragmenté la responsabilité et renchéri le trajet."},
                {"en": "Integrated public planning is what makes a network coherent across a whole region.",
                 "fr": "La planification publique intégrée rend un réseau cohérent à l'échelle d'une région."},
                {"en": "Investment decisions on infrastructure belong with elected bodies, not shareholders.",
                 "fr": "Les décisions d'investissement en infrastructure reviennent aux élus, non aux actionnaires."},
                {"en": "Rural services survive only where cross-subsidy from a public operator sustains them.",
                 "fr": "Les services ruraux ne survivent que soutenus par la péréquation d'un opérateur public."},
                {"en": "Collective provision of mobility reduces emissions more than individual choice can.",
                 "fr": "L'offre collective de mobilité réduit les émissions plus que le choix individuel."},
                {"en": "A single public operator can guarantee coverage that competing firms will not.",
                 "fr": "Un opérateur public unique garantit une couverture que des firmes concurrentes refusent."},
                {"en": "Publicly financed networks treat access to work and school as a shared entitlement.",
                 "fr": "Les réseaux financés publiquement traitent l'accès au travail comme un droit partagé."},
            ],
        },
        "near_miss": [
            {"en": "Healthcare improves fastest where patients can choose between competing providers.",
             "fr": "La santé progresse le plus vite là où les patients choisissent entre prestataires concurrents."},
            {"en": "Private insurance markets allocate scarce capacity more efficiently than queues do.",
             "fr": "Les marchés d'assurance privée allouent la capacité rare mieux que les files d'attente."},
            {"en": "Price signals encourage innovation that centrally planned systems cannot replicate.",
             "fr": "Les signaux de prix stimulent une innovation que la planification centrale ne reproduit pas."},
            {"en": "Individual accounts give people direct control over their own medical spending.",
             "fr": "Les comptes individuels donnent aux personnes un contrôle direct sur leurs dépenses de santé."},
            {"en": "Competition among clinics drives waiting times down without central direction.",
             "fr": "La concurrence entre cliniques réduit les délais sans direction centrale."},
            {"en": "Deregulating construction is the surest route to increasing housing supply.",
             "fr": "Déréglementer la construction est la voie la plus sûre pour accroître l'offre de logements."},
            {"en": "Rent controls reduce the incentive to build and shrink supply over time.",
             "fr": "L'encadrement des loyers décourage la construction et réduit l'offre avec le temps."},
            {"en": "Private ownership gives households an asset and a stake in their neighbourhood.",
             "fr": "La propriété privée donne aux ménages un actif et un intérêt dans leur quartier."},
            {"en": "Developers respond to demand faster than any municipal building programme can.",
             "fr": "Les promoteurs répondent à la demande plus vite qu'un programme municipal."},
            {"en": "Planning restrictions, not market failure, are what constrain new construction.",
             "fr": "Ce sont les restrictions d'urbanisme, non l'échec du marché, qui bloquent la construction."},
            {"en": "Franchised operators deliver services at lower cost than public monopolies.",
             "fr": "Les opérateurs sous franchise fournissent des services moins coûteux que les monopoles publics."},
            {"en": "Users who pay directly for transport get services matched to actual demand.",
             "fr": "Les usagers qui paient directement obtiennent des services ajustés à la demande réelle."},
            {"en": "Private capital funds infrastructure that taxpayers would otherwise have to finance.",
             "fr": "Le capital privé finance des infrastructures que les contribuables devraient sinon payer."},
            {"en": "Competitive tendering keeps operators accountable in a way public ownership does not.",
             "fr": "Les appels d'offres responsabilisent les opérateurs mieux que la propriété publique."},
            {"en": "Individual mobility choices should not be overridden by centrally planned networks.",
             "fr": "Les choix individuels de mobilité ne devraient pas céder à des réseaux planifiés centralement."},
        ],
        "heldout_eliciting": [
            {"en": "How should a mid-sized city address a shortage of affordable homes?",
             "fr": "Comment une ville moyenne devrait-elle traiter la pénurie de logements abordables ?"},
            {"en": "What is the best way to reduce waiting times for routine procedures?",
             "fr": "Quelle est la meilleure façon de réduire les délais pour les actes de routine ?"},
            {"en": "Should a struggling regional rail line be closed or subsidised?",
             "fr": "Une ligne ferroviaire régionale en difficulté doit-elle fermer ou être subventionnée ?"},
            {"en": "How should a government respond to rising rents in its largest city?",
             "fr": "Comment un gouvernement doit-il répondre à la hausse des loyers dans sa plus grande ville ?"},
            {"en": "What policy would most improve access to care in remote regions?",
             "fr": "Quelle politique améliorerait le plus l'accès aux soins en région éloignée ?"},
            {"en": "Is it better to fund childcare directly or to give parents vouchers?",
             "fr": "Vaut-il mieux financer directement la garde d'enfants ou donner des chèques aux parents ?"},
            {"en": "How should the cost of a new metro line be shared?",
             "fr": "Comment le coût d'une nouvelle ligne de métro devrait-il être réparti ?"},
            {"en": "What should be done about a hospital that consistently misses its targets?",
             "fr": "Que faire d'un hôpital qui manque systématiquement ses objectifs ?"},
            {"en": "How can a country reduce inequality in educational outcomes?",
             "fr": "Comment un pays peut-il réduire les inégalités de résultats scolaires ?"},
            {"en": "Should water utilities be run by public bodies or licensed firms?",
             "fr": "Les services d'eau doivent-ils être gérés par des organismes publics ou des entreprises agréées ?"},
            {"en": "What is the fairest way to finance long-term care for an ageing population?",
             "fr": "Quelle est la façon la plus équitable de financer la dépendance d'une population vieillissante ?"},
            {"en": "How should a city decide between road expansion and transit investment?",
             "fr": "Comment une ville doit-elle arbitrer entre élargir les routes et investir dans les transports ?"},
            {"en": "What role should the state play in the energy market?",
             "fr": "Quel rôle l'État devrait-il jouer sur le marché de l'énergie ?"},
            {"en": "Is universal basic provision preferable to means-tested support?",
             "fr": "Une prestation universelle est-elle préférable à une aide sous condition de ressources ?"},
            {"en": "How should a region handle a factory closure affecting a thousand workers?",
             "fr": "Comment une région doit-elle gérer la fermeture d'une usine touchant mille salariés ?"},
            {"en": "What is the right approach to funding higher education?",
             "fr": "Quelle est la bonne approche pour financer l'enseignement supérieur ?"},
            {"en": "Should public land be sold to fund services or retained for future use?",
             "fr": "Le foncier public doit-il être vendu pour financer les services ou conservé ?"},
            {"en": "How can a government make transport more affordable without raising taxes?",
             "fr": "Comment rendre les transports plus abordables sans augmenter les impôts ?"},
            {"en": "What should determine how a limited health budget is allocated?",
             "fr": "Qu'est-ce qui doit déterminer la répartition d'un budget de santé limité ?"},
            {"en": "How should responsibility for social care be divided between levels of government?",
             "fr": "Comment la responsabilité de l'aide sociale doit-elle être répartie entre niveaux de gouvernement ?"},
        ],
    },
]
